// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/v1/auth.proto

package authv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/harvesthub-gardening-tool/protos-go/auth/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v1.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/auth.v1.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/auth.v1.AuthService/Login"
	// AuthServiceCreateHubTokenProcedure is the fully-qualified name of the AuthService's
	// CreateHubToken RPC.
	AuthServiceCreateHubTokenProcedure = "/auth.v1.AuthService/CreateHubToken"
	// AuthServiceListHubTokensProcedure is the fully-qualified name of the AuthService's ListHubTokens
	// RPC.
	AuthServiceListHubTokensProcedure = "/auth.v1.AuthService/ListHubTokens"
	// AuthServiceRevokeHubTokenProcedure is the fully-qualified name of the AuthService's
	// RevokeHubToken RPC.
	AuthServiceRevokeHubTokenProcedure = "/auth.v1.AuthService/RevokeHubToken"
)

// AuthServiceClient is a client for the auth.v1.AuthService service.
type AuthServiceClient interface {
	// Public — no token required
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Protected — valid user token required
	CreateHubToken(context.Context, *connect.Request[v1.CreateHubTokenRequest]) (*connect.Response[v1.CreateHubTokenResponse], error)
	ListHubTokens(context.Context, *connect.Request[v1.ListHubTokensRequest]) (*connect.Response[v1.ListHubTokensResponse], error)
	RevokeHubToken(context.Context, *connect.Request[v1.RevokeHubTokenRequest]) (*connect.Response[v1.RevokeHubTokenResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v1.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[v1.RegisterRequest, v1.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v1.LoginRequest, v1.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		createHubToken: connect.NewClient[v1.CreateHubTokenRequest, v1.CreateHubTokenResponse](
			httpClient,
			baseURL+AuthServiceCreateHubTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("CreateHubToken")),
			connect.WithClientOptions(opts...),
		),
		listHubTokens: connect.NewClient[v1.ListHubTokensRequest, v1.ListHubTokensResponse](
			httpClient,
			baseURL+AuthServiceListHubTokensProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListHubTokens")),
			connect.WithClientOptions(opts...),
		),
		revokeHubToken: connect.NewClient[v1.RevokeHubTokenRequest, v1.RevokeHubTokenResponse](
			httpClient,
			baseURL+AuthServiceRevokeHubTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeHubToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register       *connect.Client[v1.RegisterRequest, v1.RegisterResponse]
	login          *connect.Client[v1.LoginRequest, v1.LoginResponse]
	createHubToken *connect.Client[v1.CreateHubTokenRequest, v1.CreateHubTokenResponse]
	listHubTokens  *connect.Client[v1.ListHubTokensRequest, v1.ListHubTokensResponse]
	revokeHubToken *connect.Client[v1.RevokeHubTokenRequest, v1.RevokeHubTokenResponse]
}

// Register calls auth.v1.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls auth.v1.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// CreateHubToken calls auth.v1.AuthService.CreateHubToken.
func (c *authServiceClient) CreateHubToken(ctx context.Context, req *connect.Request[v1.CreateHubTokenRequest]) (*connect.Response[v1.CreateHubTokenResponse], error) {
	return c.createHubToken.CallUnary(ctx, req)
}

// ListHubTokens calls auth.v1.AuthService.ListHubTokens.
func (c *authServiceClient) ListHubTokens(ctx context.Context, req *connect.Request[v1.ListHubTokensRequest]) (*connect.Response[v1.ListHubTokensResponse], error) {
	return c.listHubTokens.CallUnary(ctx, req)
}

// RevokeHubToken calls auth.v1.AuthService.RevokeHubToken.
func (c *authServiceClient) RevokeHubToken(ctx context.Context, req *connect.Request[v1.RevokeHubTokenRequest]) (*connect.Response[v1.RevokeHubTokenResponse], error) {
	return c.revokeHubToken.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v1.AuthService service.
type AuthServiceHandler interface {
	// Public — no token required
	Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error)
	Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error)
	// Protected — valid user token required
	CreateHubToken(context.Context, *connect.Request[v1.CreateHubTokenRequest]) (*connect.Response[v1.CreateHubTokenResponse], error)
	ListHubTokens(context.Context, *connect.Request[v1.ListHubTokensRequest]) (*connect.Response[v1.ListHubTokensResponse], error)
	RevokeHubToken(context.Context, *connect.Request[v1.RevokeHubTokenRequest]) (*connect.Response[v1.RevokeHubTokenResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v1.File_auth_v1_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceCreateHubTokenHandler := connect.NewUnaryHandler(
		AuthServiceCreateHubTokenProcedure,
		svc.CreateHubToken,
		connect.WithSchema(authServiceMethods.ByName("CreateHubToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListHubTokensHandler := connect.NewUnaryHandler(
		AuthServiceListHubTokensProcedure,
		svc.ListHubTokens,
		connect.WithSchema(authServiceMethods.ByName("ListHubTokens")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeHubTokenHandler := connect.NewUnaryHandler(
		AuthServiceRevokeHubTokenProcedure,
		svc.RevokeHubToken,
		connect.WithSchema(authServiceMethods.ByName("RevokeHubToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.v1.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceCreateHubTokenProcedure:
			authServiceCreateHubTokenHandler.ServeHTTP(w, r)
		case AuthServiceListHubTokensProcedure:
			authServiceListHubTokensHandler.ServeHTTP(w, r)
		case AuthServiceRevokeHubTokenProcedure:
			authServiceRevokeHubTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[v1.RegisterRequest]) (*connect.Response[v1.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v1.LoginRequest]) (*connect.Response[v1.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) CreateHubToken(context.Context, *connect.Request[v1.CreateHubTokenRequest]) (*connect.Response[v1.CreateHubTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.CreateHubToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListHubTokens(context.Context, *connect.Request[v1.ListHubTokensRequest]) (*connect.Response[v1.ListHubTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.ListHubTokens is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeHubToken(context.Context, *connect.Request[v1.RevokeHubTokenRequest]) (*connect.Response[v1.RevokeHubTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v1.AuthService.RevokeHubToken is not implemented"))
}
