// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v2/auth.proto

package authv2

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====== Messages ======
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AssociateHubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique device identifier (UUID) generated by the hub at first flash and printed in the QR code.
	DeviceId string `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Per-device secret (hex-encoded) printed in the QR code. Used to authenticate the hub during ClaimHubToken.
	HubSecret string `protobuf:"bytes,2,opt,name=hub_secret,json=hubSecret,proto3" json:"hub_secret,omitempty"`
	// Human-readable name chosen by the user (e.g. "Greenhouse Hub").
	HubName       string `protobuf:"bytes,3,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateHubRequest) Reset() {
	*x = AssociateHubRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateHubRequest) ProtoMessage() {}

func (x *AssociateHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateHubRequest.ProtoReflect.Descriptor instead.
func (*AssociateHubRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{4}
}

func (x *AssociateHubRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AssociateHubRequest) GetHubSecret() string {
	if x != nil {
		return x.HubSecret
	}
	return ""
}

func (x *AssociateHubRequest) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

type AssociateHubResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side hub ID (database primary key, stringified).
	HubId         string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	DeviceId      string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	HubName       string `protobuf:"bytes,3,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateHubResponse) Reset() {
	*x = AssociateHubResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateHubResponse) ProtoMessage() {}

func (x *AssociateHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateHubResponse.ProtoReflect.Descriptor instead.
func (*AssociateHubResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{5}
}

func (x *AssociateHubResponse) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *AssociateHubResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *AssociateHubResponse) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

type ClaimHubTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	HubSecret     string                 `protobuf:"bytes,2,opt,name=hub_secret,json=hubSecret,proto3" json:"hub_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimHubTokenRequest) Reset() {
	*x = ClaimHubTokenRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimHubTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimHubTokenRequest) ProtoMessage() {}

func (x *ClaimHubTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimHubTokenRequest.ProtoReflect.Descriptor instead.
func (*ClaimHubTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ClaimHubTokenRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ClaimHubTokenRequest) GetHubSecret() string {
	if x != nil {
		return x.HubSecret
	}
	return ""
}

type ClaimHubTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hub service-account JWT. Returned exactly once; the hub must persist it.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimHubTokenResponse) Reset() {
	*x = ClaimHubTokenResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimHubTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimHubTokenResponse) ProtoMessage() {}

func (x *ClaimHubTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimHubTokenResponse.ProtoReflect.Descriptor instead.
func (*ClaimHubTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{7}
}

func (x *ClaimHubTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListHubsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHubsRequest) Reset() {
	*x = ListHubsRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHubsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHubsRequest) ProtoMessage() {}

func (x *ListHubsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHubsRequest.ProtoReflect.Descriptor instead.
func (*ListHubsRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{8}
}

type HubInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side hub ID (database primary key, stringified).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DeviceId      string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	HubName       string `protobuf:"bytes,3,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	CreatedAt     int64  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix milliseconds
	Claimed       bool   `protobuf:"varint,5,opt,name=claimed,proto3" json:"claimed,omitempty"`                      // true once the hub has retrieved its JWT
	Revoked       bool   `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubInfo) Reset() {
	*x = HubInfo{}
	mi := &file_auth_v2_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubInfo) ProtoMessage() {}

func (x *HubInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubInfo.ProtoReflect.Descriptor instead.
func (*HubInfo) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{9}
}

func (x *HubInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HubInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *HubInfo) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

func (x *HubInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HubInfo) GetClaimed() bool {
	if x != nil {
		return x.Claimed
	}
	return false
}

func (x *HubInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ListHubsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hubs          []*HubInfo             `protobuf:"bytes,1,rep,name=hubs,proto3" json:"hubs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHubsResponse) Reset() {
	*x = ListHubsResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHubsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHubsResponse) ProtoMessage() {}

func (x *ListHubsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHubsResponse.ProtoReflect.Descriptor instead.
func (*ListHubsResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{10}
}

func (x *ListHubsResponse) GetHubs() []*HubInfo {
	if x != nil {
		return x.Hubs
	}
	return nil
}

type RevokeHubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-side hub ID returned by AssociateHub / ListHubs.
	HubId         string `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeHubRequest) Reset() {
	*x = RevokeHubRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeHubRequest) ProtoMessage() {}

func (x *RevokeHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeHubRequest.ProtoReflect.Descriptor instead.
func (*RevokeHubRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{11}
}

func (x *RevokeHubRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

type RevokeHubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeHubResponse) Reset() {
	*x = RevokeHubResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeHubResponse) ProtoMessage() {}

func (x *RevokeHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeHubResponse.ProtoReflect.Descriptor instead.
func (*RevokeHubResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{12}
}

type ChangeEmailRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewEmail        string                 `protobuf:"bytes,1,opt,name=new_email,json=newEmail,proto3" json:"new_email,omitempty"`
	CurrentPassword string                 `protobuf:"bytes,2,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangeEmailRequest) Reset() {
	*x = ChangeEmailRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailRequest) ProtoMessage() {}

func (x *ChangeEmailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailRequest.ProtoReflect.Descriptor instead.
func (*ChangeEmailRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{13}
}

func (x *ChangeEmailRequest) GetNewEmail() string {
	if x != nil {
		return x.NewEmail
	}
	return ""
}

func (x *ChangeEmailRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

type ChangeEmailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEmailResponse) Reset() {
	*x = ChangeEmailResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEmailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEmailResponse) ProtoMessage() {}

func (x *ChangeEmailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEmailResponse.ProtoReflect.Descriptor instead.
func (*ChangeEmailResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{14}
}

func (x *ChangeEmailResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ChangePasswordRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CurrentPassword string                 `protobuf:"bytes,1,opt,name=current_password,json=currentPassword,proto3" json:"current_password,omitempty"`
	NewPassword     string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_auth_v2_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{15}
}

func (x *ChangePasswordRequest) GetCurrentPassword() string {
	if x != nil {
		return x.CurrentPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_auth_v2_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v2_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_auth_v2_auth_proto_rawDescGZIP(), []int{16}
}

var File_auth_v2_auth_proto protoreflect.FileDescriptor

const file_auth_v2_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v2/auth.proto\x12\aauth.v2\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"l\n" +
	"\x13AssociateHubRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"hub_secret\x18\x02 \x01(\tR\thubSecret\x12\x19\n" +
	"\bhub_name\x18\x03 \x01(\tR\ahubName\"e\n" +
	"\x14AssociateHubResponse\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bhub_name\x18\x03 \x01(\tR\ahubName\"R\n" +
	"\x14ClaimHubTokenRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"hub_secret\x18\x02 \x01(\tR\thubSecret\"-\n" +
	"\x15ClaimHubTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x11\n" +
	"\x0fListHubsRequest\"\xa4\x01\n" +
	"\aHubInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bhub_name\x18\x03 \x01(\tR\ahubName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\aclaimed\x18\x05 \x01(\bR\aclaimed\x12\x18\n" +
	"\arevoked\x18\x06 \x01(\bR\arevoked\"8\n" +
	"\x10ListHubsResponse\x12$\n" +
	"\x04hubs\x18\x01 \x03(\v2\x10.auth.v2.HubInfoR\x04hubs\")\n" +
	"\x10RevokeHubRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\"\x13\n" +
	"\x11RevokeHubResponse\"\\\n" +
	"\x12ChangeEmailRequest\x12\x1b\n" +
	"\tnew_email\x18\x01 \x01(\tR\bnewEmail\x12)\n" +
	"\x10current_password\x18\x02 \x01(\tR\x0fcurrentPassword\"+\n" +
	"\x13ChangeEmailResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"e\n" +
	"\x15ChangePasswordRequest\x12)\n" +
	"\x10current_password\x18\x01 \x01(\tR\x0fcurrentPassword\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\"\x18\n" +
	"\x16ChangePasswordResponse2\xd5\x15\n" +
	"\vAuthService\x12\xdc\x01\n" +
	"\bRegister\x12\x18.auth.v2.RegisterRequest\x1a\x19.auth.v2.RegisterResponse\"\x9a\x01\x92Ao\n" +
	"\aAuth v2\x12\x19Register (AuthService v2)\x1aGCreate a new user account. Returns a user JWT token valid for 24 hours.b\x00\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/auth.v2.AuthService/Register\x12\xca\x01\n" +
	"\x05Login\x12\x15.auth.v2.LoginRequest\x1a\x16.auth.v2.LoginResponse\"\x91\x01\x92Ai\n" +
	"\aAuth v2\x12\x16Login (AuthService v2)\x1aDValidate credentials and return a user JWT token valid for 24 hours.b\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/auth.v2.AuthService/Login\x12\xb4\x04\n" +
	"\fAssociateHub\x12\x1c.auth.v2.AssociateHubRequest\x1a\x1d.auth.v2.AssociateHubResponse\"\xe6\x03\x92A\xb6\x03\n" +
	"\aAuth v2\x12\x1dAssociateHub (AuthService v2)\x1a\xfd\x02Associate a physical hub (identified by `device_id` and `hub_secret` from its QR code) with the authenticated user. Creates the Hub record and pre-generates a hub service-account JWT (valid 1 year) that the hub will later retrieve via ClaimHubToken. Fails with ALREADY_EXISTS if the device_id is already associated, or PERMISSION_DENIED if the secret does not match a known device.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02&:\x01*\"!/auth.v2.AuthService/AssociateHub\x12\xbc\x03\n" +
	"\rClaimHubToken\x12\x1d.auth.v2.ClaimHubTokenRequest\x1a\x1e.auth.v2.ClaimHubTokenResponse\"\xeb\x02\x92A\xba\x02\n" +
	"\aAuth v2\x12\x1eClaimHubToken (AuthService v2)\x1a\x8c\x02Called by a hub on first boot. Exchanges (`device_id`, `hub_secret`) for the hub JWT pre-generated during AssociateHub. Claim-once: subsequent calls for the same device fail with FAILED_PRECONDITION. The token is returned exactly once and must be persisted by the hub.b\x00\x82\xd3\xe4\x93\x02':\x01*\"\"/auth.v2.AuthService/ClaimHubToken\x12\xd6\x01\n" +
	"\bListHubs\x12\x18.auth.v2.ListHubsRequest\x1a\x19.auth.v2.ListHubsResponse\"\x94\x01\x92Ai\n" +
	"\aAuth v2\x12\x19ListHubs (AuthService v2)\x1a5List all hubs associated with the authenticated user.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/auth.v2.AuthService/ListHubs\x12\xcc\x02\n" +
	"\tRevokeHub\x12\x19.auth.v2.RevokeHubRequest\x1a\x1a.auth.v2.RevokeHubResponse\"\x87\x02\x92A\xda\x01\n" +
	"\aAuth v2\x12\x1aRevokeHub (AuthService v2)\x1a\xa4\x01Revoke the association between a hub and the authenticated user. Revokes the underlying hub token; the hub will be unable to insert sensor data until re-associated.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/auth.v2.AuthService/RevokeHub\x12\x84\x03\n" +
	"\vChangeEmail\x12\x1b.auth.v2.ChangeEmailRequest\x1a\x1c.auth.v2.ChangeEmailResponse\"\xb9\x02\x92A\x8a\x02\n" +
	"\aAuth v2\x12\x1cChangeEmail (AuthService v2)\x1a\xd2\x01Change the authenticated user's email in-app. Requires a valid user bearer token and current password confirmation; no email verification link is sent. Returns a refreshed user JWT carrying the new email claim.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02%:\x01*\" /auth.v2.AuthService/ChangeEmail\x12\xb6\x02\n" +
	"\x0eChangePassword\x12\x1e.auth.v2.ChangePasswordRequest\x1a\x1f.auth.v2.ChangePasswordResponse\"\xe2\x01\x92A\xb0\x01\n" +
	"\aAuth v2\x12\x1fChangePassword (AuthService v2)\x1avChange the authenticated user's password in-app. Requires a valid user bearer token and current password confirmation.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02(:\x01*\"#/auth.v2.AuthService/ChangePassword\x1a<\x92A9\x127User authentication and QR-based hub provisioning (v2).B\xf1\t\x92A\xae\t\x12\x92\b\n" +
	"\vAuth API v2\x12\xe6\aAuth API v2 — QR-based hub provisioning.\n" +
	"\n" +
	"**Public endpoints:** Register, Login, ClaimHubToken — no bearer token required.\n" +
	"**Protected endpoints:** AssociateHub, ListHubs, RevokeHub, ChangeEmail, ChangePassword — require a valid user Bearer token.\n" +
	"\n" +
	"**Hub provisioning flow:**\n" +
	"1. Hub is flashed with a unique `device_id` (UUID) and `hub_secret`. Both are encoded in a QR code printed on the device.\n" +
	"2. User scans the QR and calls `AssociateHub(device_id, hub_secret, hub_name)` while authenticated. The backend creates a Hub record bound to the user and pre-generates (but does not return) a hub JWT.\n" +
	"3. When the hub first reaches the internet, it calls `ClaimHubToken(device_id, hub_secret)` (public). The backend verifies the secret, returns the JWT exactly once, and marks the hub as claimed.\n" +
	"4. Subsequent hub→backend calls (e.g. InsertSensorData) authenticate with that JWT.\n" +
	"\n" +
	"A hub can only be associated with one user. `AssociateHub` is rejected if the device_id is already associated.\"\x15\n" +
	"\x13Harvest Hub Project2\x032.0*\x02\x01\x022\x10application/json2\x11application/proto:\x10application/json:\x11application/protoZI\n" +
	"G\n" +
	"\x06bearer\x12=\b\x02\x12(User JWT token. Format: 'Bearer <token>'\x1a\rAuthorization \x02Z=github.com/harvesthub-gardening-tool/protos-go/auth/v2;authv2b\x06proto3"

var (
	file_auth_v2_auth_proto_rawDescOnce sync.Once
	file_auth_v2_auth_proto_rawDescData []byte
)

func file_auth_v2_auth_proto_rawDescGZIP() []byte {
	file_auth_v2_auth_proto_rawDescOnce.Do(func() {
		file_auth_v2_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v2_auth_proto_rawDesc), len(file_auth_v2_auth_proto_rawDesc)))
	})
	return file_auth_v2_auth_proto_rawDescData
}

var file_auth_v2_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_auth_v2_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: auth.v2.RegisterRequest
	(*RegisterResponse)(nil),       // 1: auth.v2.RegisterResponse
	(*LoginRequest)(nil),           // 2: auth.v2.LoginRequest
	(*LoginResponse)(nil),          // 3: auth.v2.LoginResponse
	(*AssociateHubRequest)(nil),    // 4: auth.v2.AssociateHubRequest
	(*AssociateHubResponse)(nil),   // 5: auth.v2.AssociateHubResponse
	(*ClaimHubTokenRequest)(nil),   // 6: auth.v2.ClaimHubTokenRequest
	(*ClaimHubTokenResponse)(nil),  // 7: auth.v2.ClaimHubTokenResponse
	(*ListHubsRequest)(nil),        // 8: auth.v2.ListHubsRequest
	(*HubInfo)(nil),                // 9: auth.v2.HubInfo
	(*ListHubsResponse)(nil),       // 10: auth.v2.ListHubsResponse
	(*RevokeHubRequest)(nil),       // 11: auth.v2.RevokeHubRequest
	(*RevokeHubResponse)(nil),      // 12: auth.v2.RevokeHubResponse
	(*ChangeEmailRequest)(nil),     // 13: auth.v2.ChangeEmailRequest
	(*ChangeEmailResponse)(nil),    // 14: auth.v2.ChangeEmailResponse
	(*ChangePasswordRequest)(nil),  // 15: auth.v2.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 16: auth.v2.ChangePasswordResponse
}
var file_auth_v2_auth_proto_depIdxs = []int32{
	9,  // 0: auth.v2.ListHubsResponse.hubs:type_name -> auth.v2.HubInfo
	0,  // 1: auth.v2.AuthService.Register:input_type -> auth.v2.RegisterRequest
	2,  // 2: auth.v2.AuthService.Login:input_type -> auth.v2.LoginRequest
	4,  // 3: auth.v2.AuthService.AssociateHub:input_type -> auth.v2.AssociateHubRequest
	6,  // 4: auth.v2.AuthService.ClaimHubToken:input_type -> auth.v2.ClaimHubTokenRequest
	8,  // 5: auth.v2.AuthService.ListHubs:input_type -> auth.v2.ListHubsRequest
	11, // 6: auth.v2.AuthService.RevokeHub:input_type -> auth.v2.RevokeHubRequest
	13, // 7: auth.v2.AuthService.ChangeEmail:input_type -> auth.v2.ChangeEmailRequest
	15, // 8: auth.v2.AuthService.ChangePassword:input_type -> auth.v2.ChangePasswordRequest
	1,  // 9: auth.v2.AuthService.Register:output_type -> auth.v2.RegisterResponse
	3,  // 10: auth.v2.AuthService.Login:output_type -> auth.v2.LoginResponse
	5,  // 11: auth.v2.AuthService.AssociateHub:output_type -> auth.v2.AssociateHubResponse
	7,  // 12: auth.v2.AuthService.ClaimHubToken:output_type -> auth.v2.ClaimHubTokenResponse
	10, // 13: auth.v2.AuthService.ListHubs:output_type -> auth.v2.ListHubsResponse
	12, // 14: auth.v2.AuthService.RevokeHub:output_type -> auth.v2.RevokeHubResponse
	14, // 15: auth.v2.AuthService.ChangeEmail:output_type -> auth.v2.ChangeEmailResponse
	16, // 16: auth.v2.AuthService.ChangePassword:output_type -> auth.v2.ChangePasswordResponse
	9,  // [9:17] is the sub-list for method output_type
	1,  // [1:9] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v2_auth_proto_init() }
func file_auth_v2_auth_proto_init() {
	if File_auth_v2_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v2_auth_proto_rawDesc), len(file_auth_v2_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v2_auth_proto_goTypes,
		DependencyIndexes: file_auth_v2_auth_proto_depIdxs,
		MessageInfos:      file_auth_v2_auth_proto_msgTypes,
	}.Build()
	File_auth_v2_auth_proto = out.File
	file_auth_v2_auth_proto_goTypes = nil
	file_auth_v2_auth_proto_depIdxs = nil
}
