// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: garden/v2/garden.proto

package gardenv2

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====== Messages ======
type InsertSensorDataRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                              // Probe identifier (BLE MAC or stable hardware ID)
	AirTemperature  float64                `protobuf:"fixed64,2,opt,name=air_temperature,json=airTemperature,proto3" json:"air_temperature,omitempty"`    // Celsius
	AirHumidity     float64                `protobuf:"fixed64,3,opt,name=air_humidity,json=airHumidity,proto3" json:"air_humidity,omitempty"`             // Percent (0-100)
	SoilHumidity    float64                `protobuf:"fixed64,4,opt,name=soil_humidity,json=soilHumidity,proto3" json:"soil_humidity,omitempty"`          // Percent (0-100)
	Timestamp       int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                                     // Unix milliseconds
	AirPressure     float64                `protobuf:"fixed64,6,opt,name=air_pressure,json=airPressure,proto3" json:"air_pressure,omitempty"`             // Pascals
	SoilTemperature float64                `protobuf:"fixed64,7,opt,name=soil_temperature,json=soilTemperature,proto3" json:"soil_temperature,omitempty"` // Celsius
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InsertSensorDataRequest) Reset() {
	*x = InsertSensorDataRequest{}
	mi := &file_garden_v2_garden_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSensorDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSensorDataRequest) ProtoMessage() {}

func (x *InsertSensorDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSensorDataRequest.ProtoReflect.Descriptor instead.
func (*InsertSensorDataRequest) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{0}
}

func (x *InsertSensorDataRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *InsertSensorDataRequest) GetAirTemperature() float64 {
	if x != nil {
		return x.AirTemperature
	}
	return 0
}

func (x *InsertSensorDataRequest) GetAirHumidity() float64 {
	if x != nil {
		return x.AirHumidity
	}
	return 0
}

func (x *InsertSensorDataRequest) GetSoilHumidity() float64 {
	if x != nil {
		return x.SoilHumidity
	}
	return 0
}

func (x *InsertSensorDataRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *InsertSensorDataRequest) GetAirPressure() float64 {
	if x != nil {
		return x.AirPressure
	}
	return 0
}

func (x *InsertSensorDataRequest) GetSoilTemperature() float64 {
	if x != nil {
		return x.SoilTemperature
	}
	return 0
}

type InsertSensorDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertSensorDataResponse) Reset() {
	*x = InsertSensorDataResponse{}
	mi := &file_garden_v2_garden_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertSensorDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertSensorDataResponse) ProtoMessage() {}

func (x *InsertSensorDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertSensorDataResponse.ProtoReflect.Descriptor instead.
func (*InsertSensorDataResponse) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{1}
}

func (x *InsertSensorDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InsertSensorDataResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSummaryRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId *string                `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3,oneof" json:"node_id,omitempty"` // If empty, summarises across all nodes the caller owns.
	Hours  *int32                 `protobuf:"varint,2,opt,name=hours,proto3,oneof" json:"hours,omitempty"`                // Sliding window in hours (default 24).
	// Restrict the summary to a single hub owned by the caller. If unset, all hubs owned by the caller are included.
	HubId         *string `protobuf:"bytes,3,opt,name=hub_id,json=hubId,proto3,oneof" json:"hub_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryRequest) Reset() {
	*x = GetSummaryRequest{}
	mi := &file_garden_v2_garden_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryRequest) ProtoMessage() {}

func (x *GetSummaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryRequest.ProtoReflect.Descriptor instead.
func (*GetSummaryRequest) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{2}
}

func (x *GetSummaryRequest) GetNodeId() string {
	if x != nil && x.NodeId != nil {
		return *x.NodeId
	}
	return ""
}

func (x *GetSummaryRequest) GetHours() int32 {
	if x != nil && x.Hours != nil {
		return *x.Hours
	}
	return 0
}

func (x *GetSummaryRequest) GetHubId() string {
	if x != nil && x.HubId != nil {
		return *x.HubId
	}
	return ""
}

type GetSummaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summaries     []*SensorSummary       `protobuf:"bytes,1,rep,name=summaries,proto3" json:"summaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSummaryResponse) Reset() {
	*x = GetSummaryResponse{}
	mi := &file_garden_v2_garden_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSummaryResponse) ProtoMessage() {}

func (x *GetSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSummaryResponse.ProtoReflect.Descriptor instead.
func (*GetSummaryResponse) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{3}
}

func (x *GetSummaryResponse) GetSummaries() []*SensorSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

type SensorSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	NodeId            string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	IntervalStart     int64                  `protobuf:"varint,2,opt,name=interval_start,json=intervalStart,proto3" json:"interval_start,omitempty"`                // Unix milliseconds
	AvgAirTemperature float64                `protobuf:"fixed64,3,opt,name=avg_air_temperature,json=avgAirTemperature,proto3" json:"avg_air_temperature,omitempty"` // Celsius
	AvgAirHumidity    float64                `protobuf:"fixed64,4,opt,name=avg_air_humidity,json=avgAirHumidity,proto3" json:"avg_air_humidity,omitempty"`          // Percent (0-100)
	AvgSoilHumidity   float64                `protobuf:"fixed64,5,opt,name=avg_soil_humidity,json=avgSoilHumidity,proto3" json:"avg_soil_humidity,omitempty"`       // Percent (0-100)
	MaxAirTemperature float64                `protobuf:"fixed64,6,opt,name=max_air_temperature,json=maxAirTemperature,proto3" json:"max_air_temperature,omitempty"` // Celsius
	// ID of the hub that owns the probe (matches `hubs.id`).
	HubId              string  `protobuf:"bytes,7,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	AvgAirPressure     float64 `protobuf:"fixed64,8,opt,name=avg_air_pressure,json=avgAirPressure,proto3" json:"avg_air_pressure,omitempty"`             // Pascals
	AvgSoilTemperature float64 `protobuf:"fixed64,9,opt,name=avg_soil_temperature,json=avgSoilTemperature,proto3" json:"avg_soil_temperature,omitempty"` // Celsius
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SensorSummary) Reset() {
	*x = SensorSummary{}
	mi := &file_garden_v2_garden_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorSummary) ProtoMessage() {}

func (x *SensorSummary) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorSummary.ProtoReflect.Descriptor instead.
func (*SensorSummary) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{4}
}

func (x *SensorSummary) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SensorSummary) GetIntervalStart() int64 {
	if x != nil {
		return x.IntervalStart
	}
	return 0
}

func (x *SensorSummary) GetAvgAirTemperature() float64 {
	if x != nil {
		return x.AvgAirTemperature
	}
	return 0
}

func (x *SensorSummary) GetAvgAirHumidity() float64 {
	if x != nil {
		return x.AvgAirHumidity
	}
	return 0
}

func (x *SensorSummary) GetAvgSoilHumidity() float64 {
	if x != nil {
		return x.AvgSoilHumidity
	}
	return 0
}

func (x *SensorSummary) GetMaxAirTemperature() float64 {
	if x != nil {
		return x.MaxAirTemperature
	}
	return 0
}

func (x *SensorSummary) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *SensorSummary) GetAvgAirPressure() float64 {
	if x != nil {
		return x.AvgAirPressure
	}
	return 0
}

func (x *SensorSummary) GetAvgSoilTemperature() float64 {
	if x != nil {
		return x.AvgSoilTemperature
	}
	return 0
}

type ListProbesForHubNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable hub name (matched against the hub_name set during AssociateHub).
	HubName       string `protobuf:"bytes,1,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProbesForHubNameRequest) Reset() {
	*x = ListProbesForHubNameRequest{}
	mi := &file_garden_v2_garden_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProbesForHubNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProbesForHubNameRequest) ProtoMessage() {}

func (x *ListProbesForHubNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProbesForHubNameRequest.ProtoReflect.Descriptor instead.
func (*ListProbesForHubNameRequest) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{5}
}

func (x *ListProbesForHubNameRequest) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

type ProbeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Probe identifier (BLE MAC or stable hardware ID).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeInfo) Reset() {
	*x = ProbeInfo{}
	mi := &file_garden_v2_garden_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeInfo) ProtoMessage() {}

func (x *ProbeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeInfo.ProtoReflect.Descriptor instead.
func (*ProbeInfo) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{6}
}

func (x *ProbeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type ListProbesForHubNameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probes        []*ProbeInfo           `protobuf:"bytes,1,rep,name=probes,proto3" json:"probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProbesForHubNameResponse) Reset() {
	*x = ListProbesForHubNameResponse{}
	mi := &file_garden_v2_garden_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProbesForHubNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProbesForHubNameResponse) ProtoMessage() {}

func (x *ListProbesForHubNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProbesForHubNameResponse.ProtoReflect.Descriptor instead.
func (*ListProbesForHubNameResponse) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{7}
}

func (x *ListProbesForHubNameResponse) GetProbes() []*ProbeInfo {
	if x != nil {
		return x.Probes
	}
	return nil
}

type SensorReading struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`                              // Probe identifier (BLE MAC or stable hardware ID).
	Time            int64                  `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`                                               // Unix milliseconds of the reading timestamp.
	AirTemperature  float64                `protobuf:"fixed64,3,opt,name=air_temperature,json=airTemperature,proto3" json:"air_temperature,omitempty"`    // Celsius
	AirPressure     float64                `protobuf:"fixed64,4,opt,name=air_pressure,json=airPressure,proto3" json:"air_pressure,omitempty"`             // Pascals
	AirHumidity     float64                `protobuf:"fixed64,5,opt,name=air_humidity,json=airHumidity,proto3" json:"air_humidity,omitempty"`             // Percent (0-100)
	SoilTemperature float64                `protobuf:"fixed64,6,opt,name=soil_temperature,json=soilTemperature,proto3" json:"soil_temperature,omitempty"` // Celsius
	SoilHumidity    float64                `protobuf:"fixed64,7,opt,name=soil_humidity,json=soilHumidity,proto3" json:"soil_humidity,omitempty"`          // Percent (0-100)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SensorReading) Reset() {
	*x = SensorReading{}
	mi := &file_garden_v2_garden_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SensorReading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorReading) ProtoMessage() {}

func (x *SensorReading) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorReading.ProtoReflect.Descriptor instead.
func (*SensorReading) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{8}
}

func (x *SensorReading) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *SensorReading) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *SensorReading) GetAirTemperature() float64 {
	if x != nil {
		return x.AirTemperature
	}
	return 0
}

func (x *SensorReading) GetAirPressure() float64 {
	if x != nil {
		return x.AirPressure
	}
	return 0
}

func (x *SensorReading) GetAirHumidity() float64 {
	if x != nil {
		return x.AirHumidity
	}
	return 0
}

func (x *SensorReading) GetSoilTemperature() float64 {
	if x != nil {
		return x.SoilTemperature
	}
	return 0
}

func (x *SensorReading) GetSoilHumidity() float64 {
	if x != nil {
		return x.SoilHumidity
	}
	return 0
}

type GetLastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"` // Probe identifier (BLE MAC or stable hardware ID).
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastRequest) Reset() {
	*x = GetLastRequest{}
	mi := &file_garden_v2_garden_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastRequest) ProtoMessage() {}

func (x *GetLastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastRequest.ProtoReflect.Descriptor instead.
func (*GetLastRequest) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{9}
}

func (x *GetLastRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type GetLastResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reading       *SensorReading         `protobuf:"bytes,1,opt,name=reading,proto3" json:"reading,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLastResponse) Reset() {
	*x = GetLastResponse{}
	mi := &file_garden_v2_garden_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLastResponse) ProtoMessage() {}

func (x *GetLastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_garden_v2_garden_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLastResponse.ProtoReflect.Descriptor instead.
func (*GetLastResponse) Descriptor() ([]byte, []int) {
	return file_garden_v2_garden_proto_rawDescGZIP(), []int{10}
}

func (x *GetLastResponse) GetReading() *SensorReading {
	if x != nil {
		return x.Reading
	}
	return nil
}

var File_garden_v2_garden_proto protoreflect.FileDescriptor

const file_garden_v2_garden_proto_rawDesc = "" +
	"\n" +
	"\x16garden/v2/garden.proto\x12\tgarden.v2\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x8f\x02\n" +
	"\x17InsertSensorDataRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12'\n" +
	"\x0fair_temperature\x18\x02 \x01(\x01R\x0eairTemperature\x12!\n" +
	"\fair_humidity\x18\x03 \x01(\x01R\vairHumidity\x12#\n" +
	"\rsoil_humidity\x18\x04 \x01(\x01R\fsoilHumidity\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\x12!\n" +
	"\fair_pressure\x18\x06 \x01(\x01R\vairPressure\x12)\n" +
	"\x10soil_temperature\x18\a \x01(\x01R\x0fsoilTemperature\"N\n" +
	"\x18InsertSensorDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x89\x01\n" +
	"\x11GetSummaryRequest\x12\x1c\n" +
	"\anode_id\x18\x01 \x01(\tH\x00R\x06nodeId\x88\x01\x01\x12\x19\n" +
	"\x05hours\x18\x02 \x01(\x05H\x01R\x05hours\x88\x01\x01\x12\x1a\n" +
	"\x06hub_id\x18\x03 \x01(\tH\x02R\x05hubId\x88\x01\x01B\n" +
	"\n" +
	"\b_node_idB\b\n" +
	"\x06_hoursB\t\n" +
	"\a_hub_id\"L\n" +
	"\x12GetSummaryResponse\x126\n" +
	"\tsummaries\x18\x01 \x03(\v2\x18.garden.v2.SensorSummaryR\tsummaries\"\xf8\x02\n" +
	"\rSensorSummary\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12%\n" +
	"\x0einterval_start\x18\x02 \x01(\x03R\rintervalStart\x12.\n" +
	"\x13avg_air_temperature\x18\x03 \x01(\x01R\x11avgAirTemperature\x12(\n" +
	"\x10avg_air_humidity\x18\x04 \x01(\x01R\x0eavgAirHumidity\x12*\n" +
	"\x11avg_soil_humidity\x18\x05 \x01(\x01R\x0favgSoilHumidity\x12.\n" +
	"\x13max_air_temperature\x18\x06 \x01(\x01R\x11maxAirTemperature\x12\x15\n" +
	"\x06hub_id\x18\a \x01(\tR\x05hubId\x12(\n" +
	"\x10avg_air_pressure\x18\b \x01(\x01R\x0eavgAirPressure\x120\n" +
	"\x14avg_soil_temperature\x18\t \x01(\x01R\x12avgSoilTemperature\"8\n" +
	"\x1bListProbesForHubNameRequest\x12\x19\n" +
	"\bhub_name\x18\x01 \x01(\tR\ahubName\"$\n" +
	"\tProbeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"L\n" +
	"\x1cListProbesForHubNameResponse\x12,\n" +
	"\x06probes\x18\x01 \x03(\v2\x14.garden.v2.ProbeInfoR\x06probes\"\xfb\x01\n" +
	"\rSensorReading\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04time\x18\x02 \x01(\x03R\x04time\x12'\n" +
	"\x0fair_temperature\x18\x03 \x01(\x01R\x0eairTemperature\x12!\n" +
	"\fair_pressure\x18\x04 \x01(\x01R\vairPressure\x12!\n" +
	"\fair_humidity\x18\x05 \x01(\x01R\vairHumidity\x12)\n" +
	"\x10soil_temperature\x18\x06 \x01(\x01R\x0fsoilTemperature\x12#\n" +
	"\rsoil_humidity\x18\a \x01(\x01R\fsoilHumidity\")\n" +
	"\x0eGetLastRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\"E\n" +
	"\x0fGetLastResponse\x122\n" +
	"\areading\x18\x01 \x01(\v2\x18.garden.v2.SensorReadingR\areading2\xf8\r\n" +
	"\rGardenService\x12\x8c\x03\n" +
	"\x10InsertSensorData\x12\".garden.v2.InsertSensorDataRequest\x1a#.garden.v2.InsertSensorDataResponse\"\xae\x02\x92A\xf6\x01\n" +
	"\tGarden v2\x12#InsertSensorData (GardenService v2)\x1a\xb5\x01Insert a sensor measurement. Requires a hub service-account JWT carrying a `hub_id` claim. The probe is auto-bound to the calling hub on first sight; cross-hub spoofing is rejected.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02.:\x01*\")/garden.v2.GardenService/InsertSensorData\x12\xe0\x02\n" +
	"\n" +
	"GetSummary\x12\x1c.garden.v2.GetSummaryRequest\x1a\x1d.garden.v2.GetSummaryResponse\"\x94\x02\x92A\xe2\x01\n" +
	"\tGarden v2\x12\x1dGetSummary (GardenService v2)\x1a\xa7\x01Aggregate sensor readings over a sliding window. Users only see data from probes attached to hubs they own. Optional `hub_id` filter narrows the scope to a single hub.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02(:\x01*\"#/garden.v2.GardenService/GetSummary\x12\x80\x04\n" +
	"\x14ListProbesForHubName\x12&.garden.v2.ListProbesForHubNameRequest\x1a'.garden.v2.ListProbesForHubNameResponse\"\x96\x03\x92A\xda\x02\n" +
	"\tGarden v2\x12'ListProbesForHubName (GardenService v2)\x1a\x95\x02List all probes (sensor nodes) registered to the hub identified by `hub_name` among the hubs owned by the authenticated user. The server resolves the hub by fetching all hubs for the caller and matching on name. Returns NOT_FOUND if no hub with that name belongs to the caller.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x022:\x01*\"-/garden.v2.GardenService/ListProbesForHubName\x12\xac\x03\n" +
	"\aGetLast\x12\x19.garden.v2.GetLastRequest\x1a\x1a.garden.v2.GetLastResponse\"\xe9\x02\x92A\xba\x02\n" +
	"\tGarden v2\x12\x1aGetLast (GardenService v2)\x1a\x82\x02Returns the single most recent sensor reading for the given probe. The probe must be bound to a hub owned by the authenticated user; if the probe does not exist, has no data, or belongs to a different user, NOT_FOUND is returned. Only user JWTs are accepted.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02%:\x01*\" /garden.v2.GardenService/GetLast\x1aC\x92A@\x12>Service for collecting and retrieving garden sensor data (v2).B\xbe\x05\x92A\xf7\x04\x12\xd2\x03\n" +
	"\rGarden API v2\x12\xa4\x03API to collect and consult garden sensor data.\n" +
	"\n" +
	"**v2 changes:**\n" +
	"- Adds optional `hub_id` filter to GetSummary (lets clients scope queries to a single hub).\n" +
	"- Each `SensorSummary` now carries the `hub_id` of the hub that owns the probe.\n" +
	"- Sensor readings use explicit air/soil metric names plus air pressure.\n" +
	"\n" +
	"**Authentication:** All endpoints require Bearer token authentication (user JWT for reads, hub JWT for writes).\"\x15\n" +
	"\x13Harvest Hub Project2\x032.0*\x02\x01\x022\x10application/json2\x11application/proto:\x10application/json:\x11application/protoZD\n" +
	"B\n" +
	"\x06bearer\x128\b\x02\x12#JWT token. Format: 'Bearer <token>'\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00ZAgithub.com/harvesthub-gardening-tool/protos-go/garden/v2;gardenv2b\x06proto3"

var (
	file_garden_v2_garden_proto_rawDescOnce sync.Once
	file_garden_v2_garden_proto_rawDescData []byte
)

func file_garden_v2_garden_proto_rawDescGZIP() []byte {
	file_garden_v2_garden_proto_rawDescOnce.Do(func() {
		file_garden_v2_garden_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_garden_v2_garden_proto_rawDesc), len(file_garden_v2_garden_proto_rawDesc)))
	})
	return file_garden_v2_garden_proto_rawDescData
}

var file_garden_v2_garden_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_garden_v2_garden_proto_goTypes = []any{
	(*InsertSensorDataRequest)(nil),      // 0: garden.v2.InsertSensorDataRequest
	(*InsertSensorDataResponse)(nil),     // 1: garden.v2.InsertSensorDataResponse
	(*GetSummaryRequest)(nil),            // 2: garden.v2.GetSummaryRequest
	(*GetSummaryResponse)(nil),           // 3: garden.v2.GetSummaryResponse
	(*SensorSummary)(nil),                // 4: garden.v2.SensorSummary
	(*ListProbesForHubNameRequest)(nil),  // 5: garden.v2.ListProbesForHubNameRequest
	(*ProbeInfo)(nil),                    // 6: garden.v2.ProbeInfo
	(*ListProbesForHubNameResponse)(nil), // 7: garden.v2.ListProbesForHubNameResponse
	(*SensorReading)(nil),                // 8: garden.v2.SensorReading
	(*GetLastRequest)(nil),               // 9: garden.v2.GetLastRequest
	(*GetLastResponse)(nil),              // 10: garden.v2.GetLastResponse
}
var file_garden_v2_garden_proto_depIdxs = []int32{
	4,  // 0: garden.v2.GetSummaryResponse.summaries:type_name -> garden.v2.SensorSummary
	6,  // 1: garden.v2.ListProbesForHubNameResponse.probes:type_name -> garden.v2.ProbeInfo
	8,  // 2: garden.v2.GetLastResponse.reading:type_name -> garden.v2.SensorReading
	0,  // 3: garden.v2.GardenService.InsertSensorData:input_type -> garden.v2.InsertSensorDataRequest
	2,  // 4: garden.v2.GardenService.GetSummary:input_type -> garden.v2.GetSummaryRequest
	5,  // 5: garden.v2.GardenService.ListProbesForHubName:input_type -> garden.v2.ListProbesForHubNameRequest
	9,  // 6: garden.v2.GardenService.GetLast:input_type -> garden.v2.GetLastRequest
	1,  // 7: garden.v2.GardenService.InsertSensorData:output_type -> garden.v2.InsertSensorDataResponse
	3,  // 8: garden.v2.GardenService.GetSummary:output_type -> garden.v2.GetSummaryResponse
	7,  // 9: garden.v2.GardenService.ListProbesForHubName:output_type -> garden.v2.ListProbesForHubNameResponse
	10, // 10: garden.v2.GardenService.GetLast:output_type -> garden.v2.GetLastResponse
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_garden_v2_garden_proto_init() }
func file_garden_v2_garden_proto_init() {
	if File_garden_v2_garden_proto != nil {
		return
	}
	file_garden_v2_garden_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_garden_v2_garden_proto_rawDesc), len(file_garden_v2_garden_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_garden_v2_garden_proto_goTypes,
		DependencyIndexes: file_garden_v2_garden_proto_depIdxs,
		MessageInfos:      file_garden_v2_garden_proto_msgTypes,
	}.Build()
	File_garden_v2_garden_proto = out.File
	file_garden_v2_garden_proto_goTypes = nil
	file_garden_v2_garden_proto_depIdxs = nil
}
