// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: garden/v2/garden.proto

package gardenv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/harvesthub-gardening-tool/protos-go/garden/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// GardenServiceName is the fully-qualified name of the GardenService service.
	GardenServiceName = "garden.v2.GardenService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// GardenServiceInsertSensorDataProcedure is the fully-qualified name of the GardenService's
	// InsertSensorData RPC.
	GardenServiceInsertSensorDataProcedure = "/garden.v2.GardenService/InsertSensorData"
	// GardenServiceGetSummaryProcedure is the fully-qualified name of the GardenService's GetSummary
	// RPC.
	GardenServiceGetSummaryProcedure = "/garden.v2.GardenService/GetSummary"
	// GardenServiceListProbesForHubNameProcedure is the fully-qualified name of the GardenService's
	// ListProbesForHubName RPC.
	GardenServiceListProbesForHubNameProcedure = "/garden.v2.GardenService/ListProbesForHubName"
	// GardenServiceGetLastProcedure is the fully-qualified name of the GardenService's GetLast RPC.
	GardenServiceGetLastProcedure = "/garden.v2.GardenService/GetLast"
)

// GardenServiceClient is a client for the garden.v2.GardenService service.
type GardenServiceClient interface {
	// Insert a new sensor measurement. Hub-only.
	InsertSensorData(context.Context, *connect.Request[v2.InsertSensorDataRequest]) (*connect.Response[v2.InsertSensorDataResponse], error)
	// Read aggregated sensor data scoped to the caller's hubs.
	GetSummary(context.Context, *connect.Request[v2.GetSummaryRequest]) (*connect.Response[v2.GetSummaryResponse], error)
	// List all probes registered under a hub owned by the authenticated user. User-only.
	ListProbesForHubName(context.Context, *connect.Request[v2.ListProbesForHubNameRequest]) (*connect.Response[v2.ListProbesForHubNameResponse], error)
	// Return the most recent sensor reading for a probe owned by the caller. User-only.
	GetLast(context.Context, *connect.Request[v2.GetLastRequest]) (*connect.Response[v2.GetLastResponse], error)
}

// NewGardenServiceClient constructs a client for the garden.v2.GardenService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewGardenServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) GardenServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	gardenServiceMethods := v2.File_garden_v2_garden_proto.Services().ByName("GardenService").Methods()
	return &gardenServiceClient{
		insertSensorData: connect.NewClient[v2.InsertSensorDataRequest, v2.InsertSensorDataResponse](
			httpClient,
			baseURL+GardenServiceInsertSensorDataProcedure,
			connect.WithSchema(gardenServiceMethods.ByName("InsertSensorData")),
			connect.WithClientOptions(opts...),
		),
		getSummary: connect.NewClient[v2.GetSummaryRequest, v2.GetSummaryResponse](
			httpClient,
			baseURL+GardenServiceGetSummaryProcedure,
			connect.WithSchema(gardenServiceMethods.ByName("GetSummary")),
			connect.WithClientOptions(opts...),
		),
		listProbesForHubName: connect.NewClient[v2.ListProbesForHubNameRequest, v2.ListProbesForHubNameResponse](
			httpClient,
			baseURL+GardenServiceListProbesForHubNameProcedure,
			connect.WithSchema(gardenServiceMethods.ByName("ListProbesForHubName")),
			connect.WithClientOptions(opts...),
		),
		getLast: connect.NewClient[v2.GetLastRequest, v2.GetLastResponse](
			httpClient,
			baseURL+GardenServiceGetLastProcedure,
			connect.WithSchema(gardenServiceMethods.ByName("GetLast")),
			connect.WithClientOptions(opts...),
		),
	}
}

// gardenServiceClient implements GardenServiceClient.
type gardenServiceClient struct {
	insertSensorData     *connect.Client[v2.InsertSensorDataRequest, v2.InsertSensorDataResponse]
	getSummary           *connect.Client[v2.GetSummaryRequest, v2.GetSummaryResponse]
	listProbesForHubName *connect.Client[v2.ListProbesForHubNameRequest, v2.ListProbesForHubNameResponse]
	getLast              *connect.Client[v2.GetLastRequest, v2.GetLastResponse]
}

// InsertSensorData calls garden.v2.GardenService.InsertSensorData.
func (c *gardenServiceClient) InsertSensorData(ctx context.Context, req *connect.Request[v2.InsertSensorDataRequest]) (*connect.Response[v2.InsertSensorDataResponse], error) {
	return c.insertSensorData.CallUnary(ctx, req)
}

// GetSummary calls garden.v2.GardenService.GetSummary.
func (c *gardenServiceClient) GetSummary(ctx context.Context, req *connect.Request[v2.GetSummaryRequest]) (*connect.Response[v2.GetSummaryResponse], error) {
	return c.getSummary.CallUnary(ctx, req)
}

// ListProbesForHubName calls garden.v2.GardenService.ListProbesForHubName.
func (c *gardenServiceClient) ListProbesForHubName(ctx context.Context, req *connect.Request[v2.ListProbesForHubNameRequest]) (*connect.Response[v2.ListProbesForHubNameResponse], error) {
	return c.listProbesForHubName.CallUnary(ctx, req)
}

// GetLast calls garden.v2.GardenService.GetLast.
func (c *gardenServiceClient) GetLast(ctx context.Context, req *connect.Request[v2.GetLastRequest]) (*connect.Response[v2.GetLastResponse], error) {
	return c.getLast.CallUnary(ctx, req)
}

// GardenServiceHandler is an implementation of the garden.v2.GardenService service.
type GardenServiceHandler interface {
	// Insert a new sensor measurement. Hub-only.
	InsertSensorData(context.Context, *connect.Request[v2.InsertSensorDataRequest]) (*connect.Response[v2.InsertSensorDataResponse], error)
	// Read aggregated sensor data scoped to the caller's hubs.
	GetSummary(context.Context, *connect.Request[v2.GetSummaryRequest]) (*connect.Response[v2.GetSummaryResponse], error)
	// List all probes registered under a hub owned by the authenticated user. User-only.
	ListProbesForHubName(context.Context, *connect.Request[v2.ListProbesForHubNameRequest]) (*connect.Response[v2.ListProbesForHubNameResponse], error)
	// Return the most recent sensor reading for a probe owned by the caller. User-only.
	GetLast(context.Context, *connect.Request[v2.GetLastRequest]) (*connect.Response[v2.GetLastResponse], error)
}

// NewGardenServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewGardenServiceHandler(svc GardenServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	gardenServiceMethods := v2.File_garden_v2_garden_proto.Services().ByName("GardenService").Methods()
	gardenServiceInsertSensorDataHandler := connect.NewUnaryHandler(
		GardenServiceInsertSensorDataProcedure,
		svc.InsertSensorData,
		connect.WithSchema(gardenServiceMethods.ByName("InsertSensorData")),
		connect.WithHandlerOptions(opts...),
	)
	gardenServiceGetSummaryHandler := connect.NewUnaryHandler(
		GardenServiceGetSummaryProcedure,
		svc.GetSummary,
		connect.WithSchema(gardenServiceMethods.ByName("GetSummary")),
		connect.WithHandlerOptions(opts...),
	)
	gardenServiceListProbesForHubNameHandler := connect.NewUnaryHandler(
		GardenServiceListProbesForHubNameProcedure,
		svc.ListProbesForHubName,
		connect.WithSchema(gardenServiceMethods.ByName("ListProbesForHubName")),
		connect.WithHandlerOptions(opts...),
	)
	gardenServiceGetLastHandler := connect.NewUnaryHandler(
		GardenServiceGetLastProcedure,
		svc.GetLast,
		connect.WithSchema(gardenServiceMethods.ByName("GetLast")),
		connect.WithHandlerOptions(opts...),
	)
	return "/garden.v2.GardenService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case GardenServiceInsertSensorDataProcedure:
			gardenServiceInsertSensorDataHandler.ServeHTTP(w, r)
		case GardenServiceGetSummaryProcedure:
			gardenServiceGetSummaryHandler.ServeHTTP(w, r)
		case GardenServiceListProbesForHubNameProcedure:
			gardenServiceListProbesForHubNameHandler.ServeHTTP(w, r)
		case GardenServiceGetLastProcedure:
			gardenServiceGetLastHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedGardenServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedGardenServiceHandler struct{}

func (UnimplementedGardenServiceHandler) InsertSensorData(context.Context, *connect.Request[v2.InsertSensorDataRequest]) (*connect.Response[v2.InsertSensorDataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("garden.v2.GardenService.InsertSensorData is not implemented"))
}

func (UnimplementedGardenServiceHandler) GetSummary(context.Context, *connect.Request[v2.GetSummaryRequest]) (*connect.Response[v2.GetSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("garden.v2.GardenService.GetSummary is not implemented"))
}

func (UnimplementedGardenServiceHandler) ListProbesForHubName(context.Context, *connect.Request[v2.ListProbesForHubNameRequest]) (*connect.Response[v2.ListProbesForHubNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("garden.v2.GardenService.ListProbesForHubName is not implemented"))
}

func (UnimplementedGardenServiceHandler) GetLast(context.Context, *connect.Request[v2.GetLastRequest]) (*connect.Response[v2.GetLastResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("garden.v2.GardenService.GetLast is not implemented"))
}
