// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package authv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====== Messages ======
type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RegisterResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type CreateHubTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HubName       string                 `protobuf:"bytes,1,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHubTokenRequest) Reset() {
	*x = CreateHubTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHubTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHubTokenRequest) ProtoMessage() {}

func (x *CreateHubTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHubTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateHubTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *CreateHubTokenRequest) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

type CreateHubTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateHubTokenResponse) Reset() {
	*x = CreateHubTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateHubTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateHubTokenResponse) ProtoMessage() {}

func (x *CreateHubTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateHubTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateHubTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CreateHubTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ListHubTokensRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHubTokensRequest) Reset() {
	*x = ListHubTokensRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHubTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHubTokensRequest) ProtoMessage() {}

func (x *ListHubTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHubTokensRequest.ProtoReflect.Descriptor instead.
func (*ListHubTokensRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{6}
}

type HubTokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	HubName       string                 `protobuf:"bytes,2,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // Unix milliseconds
	Revoked       bool                   `protobuf:"varint,4,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubTokenInfo) Reset() {
	*x = HubTokenInfo{}
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubTokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubTokenInfo) ProtoMessage() {}

func (x *HubTokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubTokenInfo.ProtoReflect.Descriptor instead.
func (*HubTokenInfo) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{7}
}

func (x *HubTokenInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HubTokenInfo) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

func (x *HubTokenInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *HubTokenInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ListHubTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        []*HubTokenInfo        `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHubTokensResponse) Reset() {
	*x = ListHubTokensResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHubTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHubTokensResponse) ProtoMessage() {}

func (x *ListHubTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHubTokensResponse.ProtoReflect.Descriptor instead.
func (*ListHubTokensResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{8}
}

func (x *ListHubTokensResponse) GetTokens() []*HubTokenInfo {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RevokeHubTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeHubTokenRequest) Reset() {
	*x = RevokeHubTokenRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeHubTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeHubTokenRequest) ProtoMessage() {}

func (x *RevokeHubTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeHubTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeHubTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeHubTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type RevokeHubTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeHubTokenResponse) Reset() {
	*x = RevokeHubTokenResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeHubTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeHubTokenResponse) ProtoMessage() {}

func (x *RevokeHubTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeHubTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeHubTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{10}
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"C\n" +
	"\x0fRegisterRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"A\n" +
	"\x10RegisterResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"@\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"%\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"2\n" +
	"\x15CreateHubTokenRequest\x12\x19\n" +
	"\bhub_name\x18\x01 \x01(\tR\ahubName\".\n" +
	"\x16CreateHubTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x16\n" +
	"\x14ListHubTokensRequest\"r\n" +
	"\fHubTokenInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bhub_name\x18\x02 \x01(\tR\ahubName\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x18\n" +
	"\arevoked\x18\x04 \x01(\bR\arevoked\"F\n" +
	"\x15ListHubTokensResponse\x12-\n" +
	"\x06tokens\x18\x01 \x03(\v2\x15.auth.v1.HubTokenInfoR\x06tokens\"2\n" +
	"\x15RevokeHubTokenRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"\x18\n" +
	"\x16RevokeHubTokenResponse2\x92\n" +
	"\n" +
	"\vAuthService\x12\xd6\x01\n" +
	"\bRegister\x12\x18.auth.v1.RegisterRequest\x1a\x19.auth.v1.RegisterResponse\"\x94\x01\x92Ai\n" +
	"\x04Auth\x12\x16Register (AuthService)\x1aGCreate a new user account. Returns a user JWT token valid for 24 hours.b\x00\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/auth.v1.AuthService/Register\x12\xc4\x01\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\"\x8b\x01\x92Ac\n" +
	"\x04Auth\x12\x13Login (AuthService)\x1aDValidate credentials and return a user JWT token valid for 24 hours.b\x00\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/auth.v1.AuthService/Login\x12\x93\x02\n" +
	"\x0eCreateHubToken\x12\x1e.auth.v1.CreateHubTokenRequest\x1a\x1f.auth.v1.CreateHubTokenResponse\"\xbf\x01\x92A\x8d\x01\n" +
	"\x04Auth\x12\x1cCreateHubToken (AuthService)\x1aYCreate a hub device service account token valid for 1 year. The token is shown only once.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02(:\x01*\"#/auth.v1.AuthService/CreateHubToken\x12\xf8\x01\n" +
	"\rListHubTokens\x12\x1d.auth.v1.ListHubTokensRequest\x1a\x1e.auth.v1.ListHubTokensResponse\"\xa7\x01\x92Aw\n" +
	"\x04Auth\x12\x1bListHubTokens (AuthService)\x1aDList all active (non-revoked) hub tokens for the authenticated user.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02':\x01*\"\"/auth.v1.AuthService/ListHubTokens\x12\x96\x02\n" +
	"\x0eRevokeHubToken\x12\x1e.auth.v1.RevokeHubTokenRequest\x1a\x1f.auth.v1.RevokeHubTokenResponse\"\xc2\x01\x92A\x90\x01\n" +
	"\x04Auth\x12\x1cRevokeHubToken (AuthService)\x1a\\Revoke a hub token by ID. Revoked tokens are excluded from listings and rejected by the API.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x02(:\x01*\"#/auth.v1.AuthService/RevokeHubToken\x1a9\x92A6\x124User authentication and hub device token management.B\xf6\x03\x92A\xb3\x03\x12\x97\x02\n" +
	"\bAuth API\x12\xee\x01API for user registration, login, and hub device token management.\n" +
	"\n" +
	"**Public endpoints:** Register, Login — no token required.\n" +
	"**Protected endpoints:** CreateHubToken, ListHubTokens, RevokeHubToken — require a valid user Bearer token.\"\x15\n" +
	"\x13Harvest Hub Project2\x031.0*\x02\x01\x022\x10application/json2\x11application/proto:\x10application/json:\x11application/protoZI\n" +
	"G\n" +
	"\x06bearer\x12=\b\x02\x12(User JWT token. Format: 'Bearer <token>'\x1a\rAuthorization \x02Z=github.com/harvesthub-gardening-tool/protos-go/auth/v1;authv1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_auth_v1_auth_proto_goTypes = []any{
	(*RegisterRequest)(nil),        // 0: auth.v1.RegisterRequest
	(*RegisterResponse)(nil),       // 1: auth.v1.RegisterResponse
	(*LoginRequest)(nil),           // 2: auth.v1.LoginRequest
	(*LoginResponse)(nil),          // 3: auth.v1.LoginResponse
	(*CreateHubTokenRequest)(nil),  // 4: auth.v1.CreateHubTokenRequest
	(*CreateHubTokenResponse)(nil), // 5: auth.v1.CreateHubTokenResponse
	(*ListHubTokensRequest)(nil),   // 6: auth.v1.ListHubTokensRequest
	(*HubTokenInfo)(nil),           // 7: auth.v1.HubTokenInfo
	(*ListHubTokensResponse)(nil),  // 8: auth.v1.ListHubTokensResponse
	(*RevokeHubTokenRequest)(nil),  // 9: auth.v1.RevokeHubTokenRequest
	(*RevokeHubTokenResponse)(nil), // 10: auth.v1.RevokeHubTokenResponse
}
var file_auth_v1_auth_proto_depIdxs = []int32{
	7,  // 0: auth.v1.ListHubTokensResponse.tokens:type_name -> auth.v1.HubTokenInfo
	0,  // 1: auth.v1.AuthService.Register:input_type -> auth.v1.RegisterRequest
	2,  // 2: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	4,  // 3: auth.v1.AuthService.CreateHubToken:input_type -> auth.v1.CreateHubTokenRequest
	6,  // 4: auth.v1.AuthService.ListHubTokens:input_type -> auth.v1.ListHubTokensRequest
	9,  // 5: auth.v1.AuthService.RevokeHubToken:input_type -> auth.v1.RevokeHubTokenRequest
	1,  // 6: auth.v1.AuthService.Register:output_type -> auth.v1.RegisterResponse
	3,  // 7: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	5,  // 8: auth.v1.AuthService.CreateHubToken:output_type -> auth.v1.CreateHubTokenResponse
	8,  // 9: auth.v1.AuthService.ListHubTokens:output_type -> auth.v1.ListHubTokensResponse
	10, // 10: auth.v1.AuthService.RevokeHubToken:output_type -> auth.v1.RevokeHubTokenResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
