// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: control/v1/control.proto

package controlv1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ====== Enums ======
type MotorCommandAction int32

const (
	MotorCommandAction_MOTOR_COMMAND_ACTION_UNSPECIFIED      MotorCommandAction = 0
	MotorCommandAction_MOTOR_COMMAND_ACTION_RUN_FOR_DURATION MotorCommandAction = 1
	MotorCommandAction_MOTOR_COMMAND_ACTION_STOP             MotorCommandAction = 2
)

// Enum value maps for MotorCommandAction.
var (
	MotorCommandAction_name = map[int32]string{
		0: "MOTOR_COMMAND_ACTION_UNSPECIFIED",
		1: "MOTOR_COMMAND_ACTION_RUN_FOR_DURATION",
		2: "MOTOR_COMMAND_ACTION_STOP",
	}
	MotorCommandAction_value = map[string]int32{
		"MOTOR_COMMAND_ACTION_UNSPECIFIED":      0,
		"MOTOR_COMMAND_ACTION_RUN_FOR_DURATION": 1,
		"MOTOR_COMMAND_ACTION_STOP":             2,
	}
)

func (x MotorCommandAction) Enum() *MotorCommandAction {
	p := new(MotorCommandAction)
	*p = x
	return p
}

func (x MotorCommandAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorCommandAction) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v1_control_proto_enumTypes[0].Descriptor()
}

func (MotorCommandAction) Type() protoreflect.EnumType {
	return &file_control_v1_control_proto_enumTypes[0]
}

func (x MotorCommandAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorCommandAction.Descriptor instead.
func (MotorCommandAction) EnumDescriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

type MotorCommandStatus int32

const (
	MotorCommandStatus_MOTOR_COMMAND_STATUS_UNSPECIFIED   MotorCommandStatus = 0 // Invalid/default value.
	MotorCommandStatus_MOTOR_COMMAND_STATUS_QUEUED        MotorCommandStatus = 1
	MotorCommandStatus_MOTOR_COMMAND_STATUS_LEASED_TO_HUB MotorCommandStatus = 2
	MotorCommandStatus_MOTOR_COMMAND_STATUS_SENT_TO_PROBE MotorCommandStatus = 3
	MotorCommandStatus_MOTOR_COMMAND_STATUS_EXECUTING     MotorCommandStatus = 4
	MotorCommandStatus_MOTOR_COMMAND_STATUS_SUCCEEDED     MotorCommandStatus = 5
	MotorCommandStatus_MOTOR_COMMAND_STATUS_FAILED        MotorCommandStatus = 6
	MotorCommandStatus_MOTOR_COMMAND_STATUS_EXPIRED       MotorCommandStatus = 7
	MotorCommandStatus_MOTOR_COMMAND_STATUS_CANCELLED     MotorCommandStatus = 8
)

// Enum value maps for MotorCommandStatus.
var (
	MotorCommandStatus_name = map[int32]string{
		0: "MOTOR_COMMAND_STATUS_UNSPECIFIED",
		1: "MOTOR_COMMAND_STATUS_QUEUED",
		2: "MOTOR_COMMAND_STATUS_LEASED_TO_HUB",
		3: "MOTOR_COMMAND_STATUS_SENT_TO_PROBE",
		4: "MOTOR_COMMAND_STATUS_EXECUTING",
		5: "MOTOR_COMMAND_STATUS_SUCCEEDED",
		6: "MOTOR_COMMAND_STATUS_FAILED",
		7: "MOTOR_COMMAND_STATUS_EXPIRED",
		8: "MOTOR_COMMAND_STATUS_CANCELLED",
	}
	MotorCommandStatus_value = map[string]int32{
		"MOTOR_COMMAND_STATUS_UNSPECIFIED":   0,
		"MOTOR_COMMAND_STATUS_QUEUED":        1,
		"MOTOR_COMMAND_STATUS_LEASED_TO_HUB": 2,
		"MOTOR_COMMAND_STATUS_SENT_TO_PROBE": 3,
		"MOTOR_COMMAND_STATUS_EXECUTING":     4,
		"MOTOR_COMMAND_STATUS_SUCCEEDED":     5,
		"MOTOR_COMMAND_STATUS_FAILED":        6,
		"MOTOR_COMMAND_STATUS_EXPIRED":       7,
		"MOTOR_COMMAND_STATUS_CANCELLED":     8,
	}
)

func (x MotorCommandStatus) Enum() *MotorCommandStatus {
	p := new(MotorCommandStatus)
	*p = x
	return p
}

func (x MotorCommandStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorCommandStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v1_control_proto_enumTypes[1].Descriptor()
}

func (MotorCommandStatus) Type() protoreflect.EnumType {
	return &file_control_v1_control_proto_enumTypes[1]
}

func (x MotorCommandStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorCommandStatus.Descriptor instead.
func (MotorCommandStatus) EnumDescriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

type MotorCommandReasonCode int32

const (
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_UNSPECIFIED           MotorCommandReasonCode = 0 // NONE.
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_NONE                  MotorCommandReasonCode = 1
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_UNAUTHORIZED          MotorCommandReasonCode = 2
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_EXPIRED               MotorCommandReasonCode = 3
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_DUPLICATE             MotorCommandReasonCode = 4
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_PROBE_UNREACHABLE     MotorCommandReasonCode = 5
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_BLE_WRITE_FAILED      MotorCommandReasonCode = 6
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_UART_TIMEOUT          MotorCommandReasonCode = 7
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_UART_REJECTED         MotorCommandReasonCode = 8
	MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_SAFETY_LIMIT_EXCEEDED MotorCommandReasonCode = 9
)

// Enum value maps for MotorCommandReasonCode.
var (
	MotorCommandReasonCode_name = map[int32]string{
		0: "MOTOR_COMMAND_REASON_CODE_UNSPECIFIED",
		1: "MOTOR_COMMAND_REASON_CODE_NONE",
		2: "MOTOR_COMMAND_REASON_CODE_UNAUTHORIZED",
		3: "MOTOR_COMMAND_REASON_CODE_EXPIRED",
		4: "MOTOR_COMMAND_REASON_CODE_DUPLICATE",
		5: "MOTOR_COMMAND_REASON_CODE_PROBE_UNREACHABLE",
		6: "MOTOR_COMMAND_REASON_CODE_BLE_WRITE_FAILED",
		7: "MOTOR_COMMAND_REASON_CODE_UART_TIMEOUT",
		8: "MOTOR_COMMAND_REASON_CODE_UART_REJECTED",
		9: "MOTOR_COMMAND_REASON_CODE_SAFETY_LIMIT_EXCEEDED",
	}
	MotorCommandReasonCode_value = map[string]int32{
		"MOTOR_COMMAND_REASON_CODE_UNSPECIFIED":           0,
		"MOTOR_COMMAND_REASON_CODE_NONE":                  1,
		"MOTOR_COMMAND_REASON_CODE_UNAUTHORIZED":          2,
		"MOTOR_COMMAND_REASON_CODE_EXPIRED":               3,
		"MOTOR_COMMAND_REASON_CODE_DUPLICATE":             4,
		"MOTOR_COMMAND_REASON_CODE_PROBE_UNREACHABLE":     5,
		"MOTOR_COMMAND_REASON_CODE_BLE_WRITE_FAILED":      6,
		"MOTOR_COMMAND_REASON_CODE_UART_TIMEOUT":          7,
		"MOTOR_COMMAND_REASON_CODE_UART_REJECTED":         8,
		"MOTOR_COMMAND_REASON_CODE_SAFETY_LIMIT_EXCEEDED": 9,
	}
)

func (x MotorCommandReasonCode) Enum() *MotorCommandReasonCode {
	p := new(MotorCommandReasonCode)
	*p = x
	return p
}

func (x MotorCommandReasonCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MotorCommandReasonCode) Descriptor() protoreflect.EnumDescriptor {
	return file_control_v1_control_proto_enumTypes[2].Descriptor()
}

func (MotorCommandReasonCode) Type() protoreflect.EnumType {
	return &file_control_v1_control_proto_enumTypes[2]
}

func (x MotorCommandReasonCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MotorCommandReasonCode.Descriptor instead.
func (MotorCommandReasonCode) EnumDescriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{2}
}

// ====== Messages ======
type MotorCommand struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CommandId         string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	IdempotencyKey    string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	HubId             string                 `protobuf:"bytes,3,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	NodeId            string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Action            MotorCommandAction     `protobuf:"varint,5,opt,name=action,proto3,enum=control.v1.MotorCommandAction" json:"action,omitempty"`
	DurationMs        int32                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	RequestedByUserId string                 `protobuf:"bytes,7,opt,name=requested_by_user_id,json=requestedByUserId,proto3" json:"requested_by_user_id,omitempty"`
	CreatedAt         int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`                   // Unix milliseconds
	ExpiresAt         int64                  `protobuf:"varint,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`                   // Unix milliseconds
	LeaseExpiresAt    int64                  `protobuf:"varint,10,opt,name=lease_expires_at,json=leaseExpiresAt,proto3" json:"lease_expires_at,omitempty"` // Unix milliseconds, 0 when not leased
	Status            MotorCommandStatus     `protobuf:"varint,11,opt,name=status,proto3,enum=control.v1.MotorCommandStatus" json:"status,omitempty"`
	ReasonCode        MotorCommandReasonCode `protobuf:"varint,12,opt,name=reason_code,json=reasonCode,proto3,enum=control.v1.MotorCommandReasonCode" json:"reason_code,omitempty"`
	ReasonMessage     string                 `protobuf:"bytes,13,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MotorCommand) Reset() {
	*x = MotorCommand{}
	mi := &file_control_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MotorCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MotorCommand) ProtoMessage() {}

func (x *MotorCommand) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MotorCommand.ProtoReflect.Descriptor instead.
func (*MotorCommand) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *MotorCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *MotorCommand) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *MotorCommand) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *MotorCommand) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *MotorCommand) GetAction() MotorCommandAction {
	if x != nil {
		return x.Action
	}
	return MotorCommandAction_MOTOR_COMMAND_ACTION_UNSPECIFIED
}

func (x *MotorCommand) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MotorCommand) GetRequestedByUserId() string {
	if x != nil {
		return x.RequestedByUserId
	}
	return ""
}

func (x *MotorCommand) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *MotorCommand) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *MotorCommand) GetLeaseExpiresAt() int64 {
	if x != nil {
		return x.LeaseExpiresAt
	}
	return 0
}

func (x *MotorCommand) GetStatus() MotorCommandStatus {
	if x != nil {
		return x.Status
	}
	return MotorCommandStatus_MOTOR_COMMAND_STATUS_UNSPECIFIED
}

func (x *MotorCommand) GetReasonCode() MotorCommandReasonCode {
	if x != nil {
		return x.ReasonCode
	}
	return MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_UNSPECIFIED
}

func (x *MotorCommand) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

type CreateMotorCommandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IdempotencyKey string                 `protobuf:"bytes,1,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	HubId          string                 `protobuf:"bytes,2,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	NodeId         string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Action         MotorCommandAction     `protobuf:"varint,4,opt,name=action,proto3,enum=control.v1.MotorCommandAction" json:"action,omitempty"`
	DurationMs     int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	ExpiresAt      int64                  `protobuf:"varint,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // Unix milliseconds
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateMotorCommandRequest) Reset() {
	*x = CreateMotorCommandRequest{}
	mi := &file_control_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMotorCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMotorCommandRequest) ProtoMessage() {}

func (x *CreateMotorCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMotorCommandRequest.ProtoReflect.Descriptor instead.
func (*CreateMotorCommandRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMotorCommandRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateMotorCommandRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *CreateMotorCommandRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *CreateMotorCommandRequest) GetAction() MotorCommandAction {
	if x != nil {
		return x.Action
	}
	return MotorCommandAction_MOTOR_COMMAND_ACTION_UNSPECIFIED
}

func (x *CreateMotorCommandRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *CreateMotorCommandRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type CreateMotorCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *MotorCommand          `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMotorCommandResponse) Reset() {
	*x = CreateMotorCommandResponse{}
	mi := &file_control_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMotorCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMotorCommandResponse) ProtoMessage() {}

func (x *CreateMotorCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMotorCommandResponse.ProtoReflect.Descriptor instead.
func (*CreateMotorCommandResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMotorCommandResponse) GetCommand() *MotorCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type GetMotorCommandStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMotorCommandStatusRequest) Reset() {
	*x = GetMotorCommandStatusRequest{}
	mi := &file_control_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMotorCommandStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMotorCommandStatusRequest) ProtoMessage() {}

func (x *GetMotorCommandStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMotorCommandStatusRequest.ProtoReflect.Descriptor instead.
func (*GetMotorCommandStatusRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *GetMotorCommandStatusRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

type GetMotorCommandStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *MotorCommand          `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMotorCommandStatusResponse) Reset() {
	*x = GetMotorCommandStatusResponse{}
	mi := &file_control_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMotorCommandStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMotorCommandStatusResponse) ProtoMessage() {}

func (x *GetMotorCommandStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMotorCommandStatusResponse.ProtoReflect.Descriptor instead.
func (*GetMotorCommandStatusResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *GetMotorCommandStatusResponse) GetCommand() *MotorCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

type PullPendingMotorCommandsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	HubId           string                 `protobuf:"bytes,1,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	MaxCommands     int32                  `protobuf:"varint,2,opt,name=max_commands,json=maxCommands,proto3" json:"max_commands,omitempty"`
	LeaseDurationMs int32                  `protobuf:"varint,3,opt,name=lease_duration_ms,json=leaseDurationMs,proto3" json:"lease_duration_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PullPendingMotorCommandsRequest) Reset() {
	*x = PullPendingMotorCommandsRequest{}
	mi := &file_control_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullPendingMotorCommandsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPendingMotorCommandsRequest) ProtoMessage() {}

func (x *PullPendingMotorCommandsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPendingMotorCommandsRequest.ProtoReflect.Descriptor instead.
func (*PullPendingMotorCommandsRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *PullPendingMotorCommandsRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *PullPendingMotorCommandsRequest) GetMaxCommands() int32 {
	if x != nil {
		return x.MaxCommands
	}
	return 0
}

func (x *PullPendingMotorCommandsRequest) GetLeaseDurationMs() int32 {
	if x != nil {
		return x.LeaseDurationMs
	}
	return 0
}

type PullPendingMotorCommandsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Commands      []*MotorCommand        `protobuf:"bytes,1,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PullPendingMotorCommandsResponse) Reset() {
	*x = PullPendingMotorCommandsResponse{}
	mi := &file_control_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PullPendingMotorCommandsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PullPendingMotorCommandsResponse) ProtoMessage() {}

func (x *PullPendingMotorCommandsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PullPendingMotorCommandsResponse.ProtoReflect.Descriptor instead.
func (*PullPendingMotorCommandsResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *PullPendingMotorCommandsResponse) GetCommands() []*MotorCommand {
	if x != nil {
		return x.Commands
	}
	return nil
}

type AckMotorCommandEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	HubId         string                 `protobuf:"bytes,2,opt,name=hub_id,json=hubId,proto3" json:"hub_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Status        MotorCommandStatus     `protobuf:"varint,4,opt,name=status,proto3,enum=control.v1.MotorCommandStatus" json:"status,omitempty"`
	ReasonCode    MotorCommandReasonCode `protobuf:"varint,5,opt,name=reason_code,json=reasonCode,proto3,enum=control.v1.MotorCommandReasonCode" json:"reason_code,omitempty"`
	ReasonMessage string                 `protobuf:"bytes,6,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMotorCommandEventRequest) Reset() {
	*x = AckMotorCommandEventRequest{}
	mi := &file_control_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMotorCommandEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMotorCommandEventRequest) ProtoMessage() {}

func (x *AckMotorCommandEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMotorCommandEventRequest.ProtoReflect.Descriptor instead.
func (*AckMotorCommandEventRequest) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *AckMotorCommandEventRequest) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AckMotorCommandEventRequest) GetHubId() string {
	if x != nil {
		return x.HubId
	}
	return ""
}

func (x *AckMotorCommandEventRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AckMotorCommandEventRequest) GetStatus() MotorCommandStatus {
	if x != nil {
		return x.Status
	}
	return MotorCommandStatus_MOTOR_COMMAND_STATUS_UNSPECIFIED
}

func (x *AckMotorCommandEventRequest) GetReasonCode() MotorCommandReasonCode {
	if x != nil {
		return x.ReasonCode
	}
	return MotorCommandReasonCode_MOTOR_COMMAND_REASON_CODE_UNSPECIFIED
}

func (x *AckMotorCommandEventRequest) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

type AckMotorCommandEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       *MotorCommand          `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckMotorCommandEventResponse) Reset() {
	*x = AckMotorCommandEventResponse{}
	mi := &file_control_v1_control_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckMotorCommandEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckMotorCommandEventResponse) ProtoMessage() {}

func (x *AckMotorCommandEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_control_v1_control_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckMotorCommandEventResponse.ProtoReflect.Descriptor instead.
func (*AckMotorCommandEventResponse) Descriptor() ([]byte, []int) {
	return file_control_v1_control_proto_rawDescGZIP(), []int{8}
}

func (x *AckMotorCommandEventResponse) GetCommand() *MotorCommand {
	if x != nil {
		return x.Command
	}
	return nil
}

var File_control_v1_control_proto protoreflect.FileDescriptor

const file_control_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x18control/v1/control.proto\x12\n" +
	"control.v1\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\"\x9c\x04\n" +
	"\fMotorCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x15\n" +
	"\x06hub_id\x18\x03 \x01(\tR\x05hubId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x126\n" +
	"\x06action\x18\x05 \x01(\x0e2\x1e.control.v1.MotorCommandActionR\x06action\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x05R\n" +
	"durationMs\x12/\n" +
	"\x14requested_by_user_id\x18\a \x01(\tR\x11requestedByUserId\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\x03R\texpiresAt\x12(\n" +
	"\x10lease_expires_at\x18\n" +
	" \x01(\x03R\x0eleaseExpiresAt\x126\n" +
	"\x06status\x18\v \x01(\x0e2\x1e.control.v1.MotorCommandStatusR\x06status\x12C\n" +
	"\vreason_code\x18\f \x01(\x0e2\".control.v1.MotorCommandReasonCodeR\n" +
	"reasonCode\x12%\n" +
	"\x0ereason_message\x18\r \x01(\tR\rreasonMessage\"\xec\x01\n" +
	"\x19CreateMotorCommandRequest\x12'\n" +
	"\x0fidempotency_key\x18\x01 \x01(\tR\x0eidempotencyKey\x12\x15\n" +
	"\x06hub_id\x18\x02 \x01(\tR\x05hubId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x126\n" +
	"\x06action\x18\x04 \x01(\x0e2\x1e.control.v1.MotorCommandActionR\x06action\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\x03R\texpiresAt\"P\n" +
	"\x1aCreateMotorCommandResponse\x122\n" +
	"\acommand\x18\x01 \x01(\v2\x18.control.v1.MotorCommandR\acommand\"=\n" +
	"\x1cGetMotorCommandStatusRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\"S\n" +
	"\x1dGetMotorCommandStatusResponse\x122\n" +
	"\acommand\x18\x01 \x01(\v2\x18.control.v1.MotorCommandR\acommand\"\x87\x01\n" +
	"\x1fPullPendingMotorCommandsRequest\x12\x15\n" +
	"\x06hub_id\x18\x01 \x01(\tR\x05hubId\x12!\n" +
	"\fmax_commands\x18\x02 \x01(\x05R\vmaxCommands\x12*\n" +
	"\x11lease_duration_ms\x18\x03 \x01(\x05R\x0fleaseDurationMs\"X\n" +
	" PullPendingMotorCommandsResponse\x124\n" +
	"\bcommands\x18\x01 \x03(\v2\x18.control.v1.MotorCommandR\bcommands\"\x90\x02\n" +
	"\x1bAckMotorCommandEventRequest\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x15\n" +
	"\x06hub_id\x18\x02 \x01(\tR\x05hubId\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.control.v1.MotorCommandStatusR\x06status\x12C\n" +
	"\vreason_code\x18\x05 \x01(\x0e2\".control.v1.MotorCommandReasonCodeR\n" +
	"reasonCode\x12%\n" +
	"\x0ereason_message\x18\x06 \x01(\tR\rreasonMessage\"R\n" +
	"\x1cAckMotorCommandEventResponse\x122\n" +
	"\acommand\x18\x01 \x01(\v2\x18.control.v1.MotorCommandR\acommand*\x84\x01\n" +
	"\x12MotorCommandAction\x12$\n" +
	" MOTOR_COMMAND_ACTION_UNSPECIFIED\x10\x00\x12)\n" +
	"%MOTOR_COMMAND_ACTION_RUN_FOR_DURATION\x10\x01\x12\x1d\n" +
	"\x19MOTOR_COMMAND_ACTION_STOP\x10\x02*\xda\x02\n" +
	"\x12MotorCommandStatus\x12$\n" +
	" MOTOR_COMMAND_STATUS_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bMOTOR_COMMAND_STATUS_QUEUED\x10\x01\x12&\n" +
	"\"MOTOR_COMMAND_STATUS_LEASED_TO_HUB\x10\x02\x12&\n" +
	"\"MOTOR_COMMAND_STATUS_SENT_TO_PROBE\x10\x03\x12\"\n" +
	"\x1eMOTOR_COMMAND_STATUS_EXECUTING\x10\x04\x12\"\n" +
	"\x1eMOTOR_COMMAND_STATUS_SUCCEEDED\x10\x05\x12\x1f\n" +
	"\x1bMOTOR_COMMAND_STATUS_FAILED\x10\x06\x12 \n" +
	"\x1cMOTOR_COMMAND_STATUS_EXPIRED\x10\a\x12\"\n" +
	"\x1eMOTOR_COMMAND_STATUS_CANCELLED\x10\b*\xd2\x03\n" +
	"\x16MotorCommandReasonCode\x12)\n" +
	"%MOTOR_COMMAND_REASON_CODE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eMOTOR_COMMAND_REASON_CODE_NONE\x10\x01\x12*\n" +
	"&MOTOR_COMMAND_REASON_CODE_UNAUTHORIZED\x10\x02\x12%\n" +
	"!MOTOR_COMMAND_REASON_CODE_EXPIRED\x10\x03\x12'\n" +
	"#MOTOR_COMMAND_REASON_CODE_DUPLICATE\x10\x04\x12/\n" +
	"+MOTOR_COMMAND_REASON_CODE_PROBE_UNREACHABLE\x10\x05\x12.\n" +
	"*MOTOR_COMMAND_REASON_CODE_BLE_WRITE_FAILED\x10\x06\x12*\n" +
	"&MOTOR_COMMAND_REASON_CODE_UART_TIMEOUT\x10\a\x12+\n" +
	"'MOTOR_COMMAND_REASON_CODE_UART_REJECTED\x10\b\x123\n" +
	"/MOTOR_COMMAND_REASON_CODE_SAFETY_LIMIT_EXCEEDED\x10\t2\xf5\v\n" +
	"\x0eControlService\x12\xc5\x02\n" +
	"\x12CreateMotorCommand\x12%.control.v1.CreateMotorCommandRequest\x1a&.control.v1.CreateMotorCommandResponse\"\xdf\x01\x92A\xa3\x01\n" +
	"\n" +
	"Control v1\x12&CreateMotorCommand (ControlService v1)\x1a_Create a motor command idempotently for a target node. Intended for user-authenticated callers.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x022:\x01*\"-/control.v1.ControlService/CreateMotorCommand\x12\xdd\x02\n" +
	"\x15GetMotorCommandStatus\x12(.control.v1.GetMotorCommandStatusRequest\x1a).control.v1.GetMotorCommandStatusResponse\"\xee\x01\x92A\xaf\x01\n" +
	"\n" +
	"Control v1\x12)GetMotorCommandStatus (ControlService v1)\x1ahGet the latest lifecycle state and reason fields for a command. Intended for user-authenticated callers.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x025:\x01*\"0/control.v1.ControlService/GetMotorCommandStatus\x12\xfd\x02\n" +
	"\x18PullPendingMotorCommands\x12+.control.v1.PullPendingMotorCommandsRequest\x1a,.control.v1.PullPendingMotorCommandsResponse\"\x85\x02\x92A\xc3\x01\n" +
	"\n" +
	"Control v1\x12,PullPendingMotorCommands (ControlService v1)\x1ayPoll pending commands for the hub and return leased items for delivery to probes. Intended for hub-authenticated callers.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x028:\x01*\"3/control.v1.ControlService/PullPendingMotorCommands\x12\xe0\x02\n" +
	"\x14AckMotorCommandEvent\x12'.control.v1.AckMotorCommandEventRequest\x1a(.control.v1.AckMotorCommandEventResponse\"\xf4\x01\x92A\xb6\x01\n" +
	"\n" +
	"Control v1\x12(AckMotorCommandEvent (ControlService v1)\x1apAcknowledge command lifecycle events from hubs, including non-terminal and terminal states with reason metadata.b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00\x82\xd3\xe4\x93\x024:\x01*\"//control.v1.ControlService/AckMotorCommandEvent\x1aX\x92AU\x12SMotor command queue API with user-created commands and hub-polled acknowledgements.B\xd5\x04\x92A\x8c\x04\x12\xe7\x02\n" +
	"\x0eControl API v1\x12\xb8\x02Motor command queue API for MVP polling flow.\n" +
	"\n" +
	"**User flow:** User-authenticated clients enqueue commands and query status.\n" +
	"**Hub flow:** Hubs poll for pending commands and acknowledge delivery/execution outcomes.\n" +
	"\n" +
	"This MVP is intentionally polling-only and does not define streaming or push transport semantics.\"\x15\n" +
	"\x13Harvest Hub Project2\x031.0*\x02\x01\x022\x10application/json2\x11application/proto:\x10application/json:\x11application/protoZD\n" +
	"B\n" +
	"\x06bearer\x128\b\x02\x12#JWT token. Format: 'Bearer <token>'\x1a\rAuthorization \x02b\f\n" +
	"\n" +
	"\n" +
	"\x06bearer\x12\x00ZCgithub.com/harvesthub-gardening-tool/protos-go/control/v1;controlv1b\x06proto3"

var (
	file_control_v1_control_proto_rawDescOnce sync.Once
	file_control_v1_control_proto_rawDescData []byte
)

func file_control_v1_control_proto_rawDescGZIP() []byte {
	file_control_v1_control_proto_rawDescOnce.Do(func() {
		file_control_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)))
	})
	return file_control_v1_control_proto_rawDescData
}

var file_control_v1_control_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_control_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_control_v1_control_proto_goTypes = []any{
	(MotorCommandAction)(0),                  // 0: control.v1.MotorCommandAction
	(MotorCommandStatus)(0),                  // 1: control.v1.MotorCommandStatus
	(MotorCommandReasonCode)(0),              // 2: control.v1.MotorCommandReasonCode
	(*MotorCommand)(nil),                     // 3: control.v1.MotorCommand
	(*CreateMotorCommandRequest)(nil),        // 4: control.v1.CreateMotorCommandRequest
	(*CreateMotorCommandResponse)(nil),       // 5: control.v1.CreateMotorCommandResponse
	(*GetMotorCommandStatusRequest)(nil),     // 6: control.v1.GetMotorCommandStatusRequest
	(*GetMotorCommandStatusResponse)(nil),    // 7: control.v1.GetMotorCommandStatusResponse
	(*PullPendingMotorCommandsRequest)(nil),  // 8: control.v1.PullPendingMotorCommandsRequest
	(*PullPendingMotorCommandsResponse)(nil), // 9: control.v1.PullPendingMotorCommandsResponse
	(*AckMotorCommandEventRequest)(nil),      // 10: control.v1.AckMotorCommandEventRequest
	(*AckMotorCommandEventResponse)(nil),     // 11: control.v1.AckMotorCommandEventResponse
}
var file_control_v1_control_proto_depIdxs = []int32{
	0,  // 0: control.v1.MotorCommand.action:type_name -> control.v1.MotorCommandAction
	1,  // 1: control.v1.MotorCommand.status:type_name -> control.v1.MotorCommandStatus
	2,  // 2: control.v1.MotorCommand.reason_code:type_name -> control.v1.MotorCommandReasonCode
	0,  // 3: control.v1.CreateMotorCommandRequest.action:type_name -> control.v1.MotorCommandAction
	3,  // 4: control.v1.CreateMotorCommandResponse.command:type_name -> control.v1.MotorCommand
	3,  // 5: control.v1.GetMotorCommandStatusResponse.command:type_name -> control.v1.MotorCommand
	3,  // 6: control.v1.PullPendingMotorCommandsResponse.commands:type_name -> control.v1.MotorCommand
	1,  // 7: control.v1.AckMotorCommandEventRequest.status:type_name -> control.v1.MotorCommandStatus
	2,  // 8: control.v1.AckMotorCommandEventRequest.reason_code:type_name -> control.v1.MotorCommandReasonCode
	3,  // 9: control.v1.AckMotorCommandEventResponse.command:type_name -> control.v1.MotorCommand
	4,  // 10: control.v1.ControlService.CreateMotorCommand:input_type -> control.v1.CreateMotorCommandRequest
	6,  // 11: control.v1.ControlService.GetMotorCommandStatus:input_type -> control.v1.GetMotorCommandStatusRequest
	8,  // 12: control.v1.ControlService.PullPendingMotorCommands:input_type -> control.v1.PullPendingMotorCommandsRequest
	10, // 13: control.v1.ControlService.AckMotorCommandEvent:input_type -> control.v1.AckMotorCommandEventRequest
	5,  // 14: control.v1.ControlService.CreateMotorCommand:output_type -> control.v1.CreateMotorCommandResponse
	7,  // 15: control.v1.ControlService.GetMotorCommandStatus:output_type -> control.v1.GetMotorCommandStatusResponse
	9,  // 16: control.v1.ControlService.PullPendingMotorCommands:output_type -> control.v1.PullPendingMotorCommandsResponse
	11, // 17: control.v1.ControlService.AckMotorCommandEvent:output_type -> control.v1.AckMotorCommandEventResponse
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_control_v1_control_proto_init() }
func file_control_v1_control_proto_init() {
	if File_control_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_v1_control_proto_rawDesc), len(file_control_v1_control_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_control_v1_control_proto_goTypes,
		DependencyIndexes: file_control_v1_control_proto_depIdxs,
		EnumInfos:         file_control_v1_control_proto_enumTypes,
		MessageInfos:      file_control_v1_control_proto_msgTypes,
	}.Build()
	File_control_v1_control_proto = out.File
	file_control_v1_control_proto_goTypes = nil
	file_control_v1_control_proto_depIdxs = nil
}
