// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: auth/v2/auth.proto

package authv2connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v2 "github.com/harvesthub-gardening-tool/protos-go/auth/v2"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AuthServiceName is the fully-qualified name of the AuthService service.
	AuthServiceName = "auth.v2.AuthService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AuthServiceRegisterProcedure is the fully-qualified name of the AuthService's Register RPC.
	AuthServiceRegisterProcedure = "/auth.v2.AuthService/Register"
	// AuthServiceLoginProcedure is the fully-qualified name of the AuthService's Login RPC.
	AuthServiceLoginProcedure = "/auth.v2.AuthService/Login"
	// AuthServiceAssociateHubProcedure is the fully-qualified name of the AuthService's AssociateHub
	// RPC.
	AuthServiceAssociateHubProcedure = "/auth.v2.AuthService/AssociateHub"
	// AuthServiceClaimHubTokenProcedure is the fully-qualified name of the AuthService's ClaimHubToken
	// RPC.
	AuthServiceClaimHubTokenProcedure = "/auth.v2.AuthService/ClaimHubToken"
	// AuthServiceListHubsProcedure is the fully-qualified name of the AuthService's ListHubs RPC.
	AuthServiceListHubsProcedure = "/auth.v2.AuthService/ListHubs"
	// AuthServiceRevokeHubProcedure is the fully-qualified name of the AuthService's RevokeHub RPC.
	AuthServiceRevokeHubProcedure = "/auth.v2.AuthService/RevokeHub"
)

// AuthServiceClient is a client for the auth.v2.AuthService service.
type AuthServiceClient interface {
	// Public — no token required
	Register(context.Context, *connect.Request[v2.RegisterRequest]) (*connect.Response[v2.RegisterResponse], error)
	Login(context.Context, *connect.Request[v2.LoginRequest]) (*connect.Response[v2.LoginResponse], error)
	// Protected — valid user token required
	AssociateHub(context.Context, *connect.Request[v2.AssociateHubRequest]) (*connect.Response[v2.AssociateHubResponse], error)
	// Public — hub has no JWT yet on first boot
	ClaimHubToken(context.Context, *connect.Request[v2.ClaimHubTokenRequest]) (*connect.Response[v2.ClaimHubTokenResponse], error)
	ListHubs(context.Context, *connect.Request[v2.ListHubsRequest]) (*connect.Response[v2.ListHubsResponse], error)
	RevokeHub(context.Context, *connect.Request[v2.RevokeHubRequest]) (*connect.Response[v2.RevokeHubResponse], error)
}

// NewAuthServiceClient constructs a client for the auth.v2.AuthService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAuthServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AuthServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	authServiceMethods := v2.File_auth_v2_auth_proto.Services().ByName("AuthService").Methods()
	return &authServiceClient{
		register: connect.NewClient[v2.RegisterRequest, v2.RegisterResponse](
			httpClient,
			baseURL+AuthServiceRegisterProcedure,
			connect.WithSchema(authServiceMethods.ByName("Register")),
			connect.WithClientOptions(opts...),
		),
		login: connect.NewClient[v2.LoginRequest, v2.LoginResponse](
			httpClient,
			baseURL+AuthServiceLoginProcedure,
			connect.WithSchema(authServiceMethods.ByName("Login")),
			connect.WithClientOptions(opts...),
		),
		associateHub: connect.NewClient[v2.AssociateHubRequest, v2.AssociateHubResponse](
			httpClient,
			baseURL+AuthServiceAssociateHubProcedure,
			connect.WithSchema(authServiceMethods.ByName("AssociateHub")),
			connect.WithClientOptions(opts...),
		),
		claimHubToken: connect.NewClient[v2.ClaimHubTokenRequest, v2.ClaimHubTokenResponse](
			httpClient,
			baseURL+AuthServiceClaimHubTokenProcedure,
			connect.WithSchema(authServiceMethods.ByName("ClaimHubToken")),
			connect.WithClientOptions(opts...),
		),
		listHubs: connect.NewClient[v2.ListHubsRequest, v2.ListHubsResponse](
			httpClient,
			baseURL+AuthServiceListHubsProcedure,
			connect.WithSchema(authServiceMethods.ByName("ListHubs")),
			connect.WithClientOptions(opts...),
		),
		revokeHub: connect.NewClient[v2.RevokeHubRequest, v2.RevokeHubResponse](
			httpClient,
			baseURL+AuthServiceRevokeHubProcedure,
			connect.WithSchema(authServiceMethods.ByName("RevokeHub")),
			connect.WithClientOptions(opts...),
		),
	}
}

// authServiceClient implements AuthServiceClient.
type authServiceClient struct {
	register      *connect.Client[v2.RegisterRequest, v2.RegisterResponse]
	login         *connect.Client[v2.LoginRequest, v2.LoginResponse]
	associateHub  *connect.Client[v2.AssociateHubRequest, v2.AssociateHubResponse]
	claimHubToken *connect.Client[v2.ClaimHubTokenRequest, v2.ClaimHubTokenResponse]
	listHubs      *connect.Client[v2.ListHubsRequest, v2.ListHubsResponse]
	revokeHub     *connect.Client[v2.RevokeHubRequest, v2.RevokeHubResponse]
}

// Register calls auth.v2.AuthService.Register.
func (c *authServiceClient) Register(ctx context.Context, req *connect.Request[v2.RegisterRequest]) (*connect.Response[v2.RegisterResponse], error) {
	return c.register.CallUnary(ctx, req)
}

// Login calls auth.v2.AuthService.Login.
func (c *authServiceClient) Login(ctx context.Context, req *connect.Request[v2.LoginRequest]) (*connect.Response[v2.LoginResponse], error) {
	return c.login.CallUnary(ctx, req)
}

// AssociateHub calls auth.v2.AuthService.AssociateHub.
func (c *authServiceClient) AssociateHub(ctx context.Context, req *connect.Request[v2.AssociateHubRequest]) (*connect.Response[v2.AssociateHubResponse], error) {
	return c.associateHub.CallUnary(ctx, req)
}

// ClaimHubToken calls auth.v2.AuthService.ClaimHubToken.
func (c *authServiceClient) ClaimHubToken(ctx context.Context, req *connect.Request[v2.ClaimHubTokenRequest]) (*connect.Response[v2.ClaimHubTokenResponse], error) {
	return c.claimHubToken.CallUnary(ctx, req)
}

// ListHubs calls auth.v2.AuthService.ListHubs.
func (c *authServiceClient) ListHubs(ctx context.Context, req *connect.Request[v2.ListHubsRequest]) (*connect.Response[v2.ListHubsResponse], error) {
	return c.listHubs.CallUnary(ctx, req)
}

// RevokeHub calls auth.v2.AuthService.RevokeHub.
func (c *authServiceClient) RevokeHub(ctx context.Context, req *connect.Request[v2.RevokeHubRequest]) (*connect.Response[v2.RevokeHubResponse], error) {
	return c.revokeHub.CallUnary(ctx, req)
}

// AuthServiceHandler is an implementation of the auth.v2.AuthService service.
type AuthServiceHandler interface {
	// Public — no token required
	Register(context.Context, *connect.Request[v2.RegisterRequest]) (*connect.Response[v2.RegisterResponse], error)
	Login(context.Context, *connect.Request[v2.LoginRequest]) (*connect.Response[v2.LoginResponse], error)
	// Protected — valid user token required
	AssociateHub(context.Context, *connect.Request[v2.AssociateHubRequest]) (*connect.Response[v2.AssociateHubResponse], error)
	// Public — hub has no JWT yet on first boot
	ClaimHubToken(context.Context, *connect.Request[v2.ClaimHubTokenRequest]) (*connect.Response[v2.ClaimHubTokenResponse], error)
	ListHubs(context.Context, *connect.Request[v2.ListHubsRequest]) (*connect.Response[v2.ListHubsResponse], error)
	RevokeHub(context.Context, *connect.Request[v2.RevokeHubRequest]) (*connect.Response[v2.RevokeHubResponse], error)
}

// NewAuthServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAuthServiceHandler(svc AuthServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	authServiceMethods := v2.File_auth_v2_auth_proto.Services().ByName("AuthService").Methods()
	authServiceRegisterHandler := connect.NewUnaryHandler(
		AuthServiceRegisterProcedure,
		svc.Register,
		connect.WithSchema(authServiceMethods.ByName("Register")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceLoginHandler := connect.NewUnaryHandler(
		AuthServiceLoginProcedure,
		svc.Login,
		connect.WithSchema(authServiceMethods.ByName("Login")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceAssociateHubHandler := connect.NewUnaryHandler(
		AuthServiceAssociateHubProcedure,
		svc.AssociateHub,
		connect.WithSchema(authServiceMethods.ByName("AssociateHub")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceClaimHubTokenHandler := connect.NewUnaryHandler(
		AuthServiceClaimHubTokenProcedure,
		svc.ClaimHubToken,
		connect.WithSchema(authServiceMethods.ByName("ClaimHubToken")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceListHubsHandler := connect.NewUnaryHandler(
		AuthServiceListHubsProcedure,
		svc.ListHubs,
		connect.WithSchema(authServiceMethods.ByName("ListHubs")),
		connect.WithHandlerOptions(opts...),
	)
	authServiceRevokeHubHandler := connect.NewUnaryHandler(
		AuthServiceRevokeHubProcedure,
		svc.RevokeHub,
		connect.WithSchema(authServiceMethods.ByName("RevokeHub")),
		connect.WithHandlerOptions(opts...),
	)
	return "/auth.v2.AuthService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AuthServiceRegisterProcedure:
			authServiceRegisterHandler.ServeHTTP(w, r)
		case AuthServiceLoginProcedure:
			authServiceLoginHandler.ServeHTTP(w, r)
		case AuthServiceAssociateHubProcedure:
			authServiceAssociateHubHandler.ServeHTTP(w, r)
		case AuthServiceClaimHubTokenProcedure:
			authServiceClaimHubTokenHandler.ServeHTTP(w, r)
		case AuthServiceListHubsProcedure:
			authServiceListHubsHandler.ServeHTTP(w, r)
		case AuthServiceRevokeHubProcedure:
			authServiceRevokeHubHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(context.Context, *connect.Request[v2.RegisterRequest]) (*connect.Response[v2.RegisterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v2.AuthService.Register is not implemented"))
}

func (UnimplementedAuthServiceHandler) Login(context.Context, *connect.Request[v2.LoginRequest]) (*connect.Response[v2.LoginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v2.AuthService.Login is not implemented"))
}

func (UnimplementedAuthServiceHandler) AssociateHub(context.Context, *connect.Request[v2.AssociateHubRequest]) (*connect.Response[v2.AssociateHubResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v2.AuthService.AssociateHub is not implemented"))
}

func (UnimplementedAuthServiceHandler) ClaimHubToken(context.Context, *connect.Request[v2.ClaimHubTokenRequest]) (*connect.Response[v2.ClaimHubTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v2.AuthService.ClaimHubToken is not implemented"))
}

func (UnimplementedAuthServiceHandler) ListHubs(context.Context, *connect.Request[v2.ListHubsRequest]) (*connect.Response[v2.ListHubsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v2.AuthService.ListHubs is not implemented"))
}

func (UnimplementedAuthServiceHandler) RevokeHub(context.Context, *connect.Request[v2.RevokeHubRequest]) (*connect.Response[v2.RevokeHubResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("auth.v2.AuthService.RevokeHub is not implemented"))
}
