// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: control/v1/control.proto

package controlv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/harvesthub-gardening-tool/protos-go/control/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ControlServiceName is the fully-qualified name of the ControlService service.
	ControlServiceName = "control.v1.ControlService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ControlServiceCreateMotorCommandProcedure is the fully-qualified name of the ControlService's
	// CreateMotorCommand RPC.
	ControlServiceCreateMotorCommandProcedure = "/control.v1.ControlService/CreateMotorCommand"
	// ControlServiceGetMotorCommandStatusProcedure is the fully-qualified name of the ControlService's
	// GetMotorCommandStatus RPC.
	ControlServiceGetMotorCommandStatusProcedure = "/control.v1.ControlService/GetMotorCommandStatus"
	// ControlServicePullPendingMotorCommandsProcedure is the fully-qualified name of the
	// ControlService's PullPendingMotorCommands RPC.
	ControlServicePullPendingMotorCommandsProcedure = "/control.v1.ControlService/PullPendingMotorCommands"
	// ControlServiceAckMotorCommandEventProcedure is the fully-qualified name of the ControlService's
	// AckMotorCommandEvent RPC.
	ControlServiceAckMotorCommandEventProcedure = "/control.v1.ControlService/AckMotorCommandEvent"
)

// ControlServiceClient is a client for the control.v1.ControlService service.
type ControlServiceClient interface {
	// User-created RPC: enqueue a motor command for a node behind a hub.
	CreateMotorCommand(context.Context, *connect.Request[v1.CreateMotorCommandRequest]) (*connect.Response[v1.CreateMotorCommandResponse], error)
	// User-created RPC: retrieve the current status of a previously-created command.
	GetMotorCommandStatus(context.Context, *connect.Request[v1.GetMotorCommandStatusRequest]) (*connect.Response[v1.GetMotorCommandStatusResponse], error)
	// Hub-polled RPC: pull pending commands and lease them to the polling hub for bounded execution.
	PullPendingMotorCommands(context.Context, *connect.Request[v1.PullPendingMotorCommandsRequest]) (*connect.Response[v1.PullPendingMotorCommandsResponse], error)
	// Hub-ack RPC: acknowledge delivery/execution progress and terminal outcomes for a command.
	AckMotorCommandEvent(context.Context, *connect.Request[v1.AckMotorCommandEventRequest]) (*connect.Response[v1.AckMotorCommandEventResponse], error)
}

// NewControlServiceClient constructs a client for the control.v1.ControlService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewControlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ControlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	controlServiceMethods := v1.File_control_v1_control_proto.Services().ByName("ControlService").Methods()
	return &controlServiceClient{
		createMotorCommand: connect.NewClient[v1.CreateMotorCommandRequest, v1.CreateMotorCommandResponse](
			httpClient,
			baseURL+ControlServiceCreateMotorCommandProcedure,
			connect.WithSchema(controlServiceMethods.ByName("CreateMotorCommand")),
			connect.WithClientOptions(opts...),
		),
		getMotorCommandStatus: connect.NewClient[v1.GetMotorCommandStatusRequest, v1.GetMotorCommandStatusResponse](
			httpClient,
			baseURL+ControlServiceGetMotorCommandStatusProcedure,
			connect.WithSchema(controlServiceMethods.ByName("GetMotorCommandStatus")),
			connect.WithClientOptions(opts...),
		),
		pullPendingMotorCommands: connect.NewClient[v1.PullPendingMotorCommandsRequest, v1.PullPendingMotorCommandsResponse](
			httpClient,
			baseURL+ControlServicePullPendingMotorCommandsProcedure,
			connect.WithSchema(controlServiceMethods.ByName("PullPendingMotorCommands")),
			connect.WithClientOptions(opts...),
		),
		ackMotorCommandEvent: connect.NewClient[v1.AckMotorCommandEventRequest, v1.AckMotorCommandEventResponse](
			httpClient,
			baseURL+ControlServiceAckMotorCommandEventProcedure,
			connect.WithSchema(controlServiceMethods.ByName("AckMotorCommandEvent")),
			connect.WithClientOptions(opts...),
		),
	}
}

// controlServiceClient implements ControlServiceClient.
type controlServiceClient struct {
	createMotorCommand       *connect.Client[v1.CreateMotorCommandRequest, v1.CreateMotorCommandResponse]
	getMotorCommandStatus    *connect.Client[v1.GetMotorCommandStatusRequest, v1.GetMotorCommandStatusResponse]
	pullPendingMotorCommands *connect.Client[v1.PullPendingMotorCommandsRequest, v1.PullPendingMotorCommandsResponse]
	ackMotorCommandEvent     *connect.Client[v1.AckMotorCommandEventRequest, v1.AckMotorCommandEventResponse]
}

// CreateMotorCommand calls control.v1.ControlService.CreateMotorCommand.
func (c *controlServiceClient) CreateMotorCommand(ctx context.Context, req *connect.Request[v1.CreateMotorCommandRequest]) (*connect.Response[v1.CreateMotorCommandResponse], error) {
	return c.createMotorCommand.CallUnary(ctx, req)
}

// GetMotorCommandStatus calls control.v1.ControlService.GetMotorCommandStatus.
func (c *controlServiceClient) GetMotorCommandStatus(ctx context.Context, req *connect.Request[v1.GetMotorCommandStatusRequest]) (*connect.Response[v1.GetMotorCommandStatusResponse], error) {
	return c.getMotorCommandStatus.CallUnary(ctx, req)
}

// PullPendingMotorCommands calls control.v1.ControlService.PullPendingMotorCommands.
func (c *controlServiceClient) PullPendingMotorCommands(ctx context.Context, req *connect.Request[v1.PullPendingMotorCommandsRequest]) (*connect.Response[v1.PullPendingMotorCommandsResponse], error) {
	return c.pullPendingMotorCommands.CallUnary(ctx, req)
}

// AckMotorCommandEvent calls control.v1.ControlService.AckMotorCommandEvent.
func (c *controlServiceClient) AckMotorCommandEvent(ctx context.Context, req *connect.Request[v1.AckMotorCommandEventRequest]) (*connect.Response[v1.AckMotorCommandEventResponse], error) {
	return c.ackMotorCommandEvent.CallUnary(ctx, req)
}

// ControlServiceHandler is an implementation of the control.v1.ControlService service.
type ControlServiceHandler interface {
	// User-created RPC: enqueue a motor command for a node behind a hub.
	CreateMotorCommand(context.Context, *connect.Request[v1.CreateMotorCommandRequest]) (*connect.Response[v1.CreateMotorCommandResponse], error)
	// User-created RPC: retrieve the current status of a previously-created command.
	GetMotorCommandStatus(context.Context, *connect.Request[v1.GetMotorCommandStatusRequest]) (*connect.Response[v1.GetMotorCommandStatusResponse], error)
	// Hub-polled RPC: pull pending commands and lease them to the polling hub for bounded execution.
	PullPendingMotorCommands(context.Context, *connect.Request[v1.PullPendingMotorCommandsRequest]) (*connect.Response[v1.PullPendingMotorCommandsResponse], error)
	// Hub-ack RPC: acknowledge delivery/execution progress and terminal outcomes for a command.
	AckMotorCommandEvent(context.Context, *connect.Request[v1.AckMotorCommandEventRequest]) (*connect.Response[v1.AckMotorCommandEventResponse], error)
}

// NewControlServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewControlServiceHandler(svc ControlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	controlServiceMethods := v1.File_control_v1_control_proto.Services().ByName("ControlService").Methods()
	controlServiceCreateMotorCommandHandler := connect.NewUnaryHandler(
		ControlServiceCreateMotorCommandProcedure,
		svc.CreateMotorCommand,
		connect.WithSchema(controlServiceMethods.ByName("CreateMotorCommand")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceGetMotorCommandStatusHandler := connect.NewUnaryHandler(
		ControlServiceGetMotorCommandStatusProcedure,
		svc.GetMotorCommandStatus,
		connect.WithSchema(controlServiceMethods.ByName("GetMotorCommandStatus")),
		connect.WithHandlerOptions(opts...),
	)
	controlServicePullPendingMotorCommandsHandler := connect.NewUnaryHandler(
		ControlServicePullPendingMotorCommandsProcedure,
		svc.PullPendingMotorCommands,
		connect.WithSchema(controlServiceMethods.ByName("PullPendingMotorCommands")),
		connect.WithHandlerOptions(opts...),
	)
	controlServiceAckMotorCommandEventHandler := connect.NewUnaryHandler(
		ControlServiceAckMotorCommandEventProcedure,
		svc.AckMotorCommandEvent,
		connect.WithSchema(controlServiceMethods.ByName("AckMotorCommandEvent")),
		connect.WithHandlerOptions(opts...),
	)
	return "/control.v1.ControlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ControlServiceCreateMotorCommandProcedure:
			controlServiceCreateMotorCommandHandler.ServeHTTP(w, r)
		case ControlServiceGetMotorCommandStatusProcedure:
			controlServiceGetMotorCommandStatusHandler.ServeHTTP(w, r)
		case ControlServicePullPendingMotorCommandsProcedure:
			controlServicePullPendingMotorCommandsHandler.ServeHTTP(w, r)
		case ControlServiceAckMotorCommandEventProcedure:
			controlServiceAckMotorCommandEventHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedControlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedControlServiceHandler struct{}

func (UnimplementedControlServiceHandler) CreateMotorCommand(context.Context, *connect.Request[v1.CreateMotorCommandRequest]) (*connect.Response[v1.CreateMotorCommandResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("control.v1.ControlService.CreateMotorCommand is not implemented"))
}

func (UnimplementedControlServiceHandler) GetMotorCommandStatus(context.Context, *connect.Request[v1.GetMotorCommandStatusRequest]) (*connect.Response[v1.GetMotorCommandStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("control.v1.ControlService.GetMotorCommandStatus is not implemented"))
}

func (UnimplementedControlServiceHandler) PullPendingMotorCommands(context.Context, *connect.Request[v1.PullPendingMotorCommandsRequest]) (*connect.Response[v1.PullPendingMotorCommandsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("control.v1.ControlService.PullPendingMotorCommands is not implemented"))
}

func (UnimplementedControlServiceHandler) AckMotorCommandEvent(context.Context, *connect.Request[v1.AckMotorCommandEventRequest]) (*connect.Response[v1.AckMotorCommandEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("control.v1.ControlService.AckMotorCommandEvent is not implemented"))
}
